# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'details.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MAIN(object):
    def setupUi(self, MAIN):
        MAIN.setObjectName("MAIN")
        MAIN.resize(468, 887)
        MAIN.setMinimumSize(QtCore.QSize(468, 887))
        MAIN.setMaximumSize(QtCore.QSize(468, 887))
        self.label = QtWidgets.QLabel(MAIN)
        self.label.setGeometry(QtCore.QRect(0, 0, 463, 901))
        self.label.setMinimumSize(QtCore.QSize(463, 901))
        self.label.setMaximumSize(QtCore.QSize(463, 901))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/phone.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.detailsFrame = QtWidgets.QFrame(MAIN)
        self.detailsFrame.setGeometry(QtCore.QRect(31, 58, 401, 772))
        self.detailsFrame.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0.0738636 #205AFF, stop:0.840909 #1180FF);")
        self.detailsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.detailsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.detailsFrame.setObjectName("detailsFrame")
        self.detailsSlot1 = QtWidgets.QPushButton(self.detailsFrame)
        self.detailsSlot1.setGeometry(QtCore.QRect(15, 80, 371, 61))
        self.detailsSlot1.setStyleSheet("background-color: #01A7FF;\n"
"border:0px;\n"
"border-radius:20px;")
        self.detailsSlot1.setText("")
        self.detailsSlot1.setObjectName("detailsSlot1")
        self.detailsYandex = QtWidgets.QLabel(self.detailsFrame)
        self.detailsYandex.setGeometry(QtCore.QRect(300, 660, 60, 60))
        self.detailsYandex.setStyleSheet("background: rgb(0,0,0,0);")
        self.detailsYandex.setText("")
        self.detailsYandex.setPixmap(QtGui.QPixmap("img/yandexmus.png"))
        self.detailsYandex.setScaledContents(True)
        self.detailsYandex.setObjectName("detailsYandex")
        self.detailsSongName = QtWidgets.QLabel(self.detailsFrame)
        self.detailsSongName.setGeometry(QtCore.QRect(15, 90, 371, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.detailsSongName.setFont(font)
        self.detailsSongName.setStyleSheet("background: rgb(0,0,0,0);")
        self.detailsSongName.setAlignment(QtCore.Qt.AlignCenter)
        self.detailsSongName.setObjectName("detailsSongName")
        self.detailsArtist = QtWidgets.QLabel(self.detailsFrame)
        self.detailsArtist.setGeometry(QtCore.QRect(10, 110, 371, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.detailsArtist.setFont(font)
        self.detailsArtist.setStyleSheet("background: rgb(0,0,0,0);\n"
"color:#d3d4e0;")
        self.detailsArtist.setAlignment(QtCore.Qt.AlignCenter)
        self.detailsArtist.setObjectName("detailsArtist")
        self.detailsYou = QtWidgets.QLabel(self.detailsFrame)
        self.detailsYou.setGeometry(QtCore.QRect(213, 660, 60, 60))
        self.detailsYou.setStyleSheet("background: rgb(0,0,0,0);")
        self.detailsYou.setText("")
        self.detailsYou.setPixmap(QtGui.QPixmap("img/youtub.png"))
        self.detailsYou.setScaledContents(True)
        self.detailsYou.setObjectName("detailsYou")
        self.detailsOpt = QtWidgets.QLabel(self.detailsFrame)
        self.detailsOpt.setGeometry(QtCore.QRect(335, 627, 31, 30))
        self.detailsOpt.setStyleSheet("background: rgb(0,0,0,0);")
        self.detailsOpt.setText("")
        self.detailsOpt.setPixmap(QtGui.QPixmap("img/options.png"))
        self.detailsOpt.setScaledContents(True)
        self.detailsOpt.setObjectName("detailsOpt")
        self.detailsApple = QtWidgets.QLabel(self.detailsFrame)
        self.detailsApple.setGeometry(QtCore.QRect(127, 660, 65, 65))
        self.detailsApple.setStyleSheet("background: rgb(0,0,0,0);")
        self.detailsApple.setText("")
        self.detailsApple.setPixmap(QtGui.QPixmap("img/apple.png"))
        self.detailsApple.setScaledContents(True)
        self.detailsApple.setObjectName("detailsApple")
        self.detailsSpotify = QtWidgets.QLabel(self.detailsFrame)
        self.detailsSpotify.setGeometry(QtCore.QRect(41, 660, 60, 60))
        self.detailsSpotify.setStyleSheet("background: rgb(0,0,0,0);")
        self.detailsSpotify.setText("")
        self.detailsSpotify.setPixmap(QtGui.QPixmap("img/spotify.png"))
        self.detailsSpotify.setScaledContents(True)
        self.detailsSpotify.setObjectName("detailsSpotify")
        self.detailsSlot3 = QtWidgets.QPushButton(self.detailsFrame)
        self.detailsSlot3.setGeometry(QtCore.QRect(15, 620, 371, 141))
        self.detailsSlot3.setStyleSheet("background-color: #01A7FF;\n"
"border:0px;\n"
"border-radius:20px;")
        self.detailsSlot3.setText("")
        self.detailsSlot3.setObjectName("detailsSlot3")
        self.detailsTopLabel = QtWidgets.QLabel(self.detailsFrame)
        self.detailsTopLabel.setGeometry(QtCore.QRect(0, 30, 401, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(11)
        self.detailsTopLabel.setFont(font)
        self.detailsTopLabel.setStyleSheet("color:white;\n"
"background: rgb(0,0,0,0);")
        self.detailsTopLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.detailsTopLabel.setObjectName("detailsTopLabel")
        self.detailsBackBut = QtWidgets.QLabel(self.detailsFrame)
        self.detailsBackBut.setGeometry(QtCore.QRect(20, 20, 40, 40))
        self.detailsBackBut.setStyleSheet("background: rgb(0,0,0,0);")
        self.detailsBackBut.setText("")
        self.detailsBackBut.setPixmap(QtGui.QPixmap("img/back.png"))
        self.detailsBackBut.setScaledContents(True)
        self.detailsBackBut.setObjectName("detailsBackBut")
        self.detailsPlayLabel = QtWidgets.QLabel(self.detailsFrame)
        self.detailsPlayLabel.setGeometry(QtCore.QRect(40, 630, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.detailsPlayLabel.setFont(font)
        self.detailsPlayLabel.setStyleSheet("background: rgb(0,0,0,0);\n"
"color:black;")
        self.detailsPlayLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.detailsPlayLabel.setObjectName("detailsPlayLabel")
        self.detailsTable = QtWidgets.QTableWidget(self.detailsFrame)
        self.detailsTable.setGeometry(QtCore.QRect(0, 216, 401, 391))
        self.detailsTable.setStyleSheet("background:white;\n"
"border:0px;")
        self.detailsTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.detailsTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.detailsTable.setShowGrid(True)
        self.detailsTable.setObjectName("detailsTable")
        self.detailsTable.setColumnCount(3)
        self.detailsTable.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.detailsTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailsTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailsTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailsTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailsTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailsTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailsTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.detailsTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailsTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailsTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(97, 212, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.detailsTable.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailsTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailsTable.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.detailsTable.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailsTable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailsTable.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(97, 212, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.detailsTable.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailsTable.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailsTable.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(97, 212, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.detailsTable.setItem(4, 2, item)
        self.detailsTable.horizontalHeader().setVisible(True)
        self.detailsTable.horizontalHeader().setCascadingSectionResizes(False)
        self.detailsTable.horizontalHeader().setHighlightSections(True)
        self.detailsTable.horizontalHeader().setSortIndicatorShown(False)
        self.detailsTable.horizontalHeader().setStretchLastSection(True)
        self.detailsTable.verticalHeader().setVisible(False)
        self.detailsTable.verticalHeader().setCascadingSectionResizes(False)
        self.detailsTable.verticalHeader().setHighlightSections(True)
        self.detailsTable.verticalHeader().setSortIndicatorShown(False)
        self.detailsTable.verticalHeader().setStretchLastSection(False)
        self.detailsSpotifyLabel = QtWidgets.QLabel(self.detailsFrame)
        self.detailsSpotifyLabel.setGeometry(QtCore.QRect(40, 720, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(9)
        self.detailsSpotifyLabel.setFont(font)
        self.detailsSpotifyLabel.setStyleSheet("color:white;\n"
"background: rgb(0,0,0,0);")
        self.detailsSpotifyLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.detailsSpotifyLabel.setObjectName("detailsSpotifyLabel")
        self.detailsAppleLabel = QtWidgets.QLabel(self.detailsFrame)
        self.detailsAppleLabel.setGeometry(QtCore.QRect(133, 710, 51, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(8)
        self.detailsAppleLabel.setFont(font)
        self.detailsAppleLabel.setStyleSheet("color:white;\n"
"background: rgb(0,0,0,0);")
        self.detailsAppleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.detailsAppleLabel.setObjectName("detailsAppleLabel")
        self.detailsYouLabel = QtWidgets.QLabel(self.detailsFrame)
        self.detailsYouLabel.setGeometry(QtCore.QRect(215, 720, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(9)
        self.detailsYouLabel.setFont(font)
        self.detailsYouLabel.setStyleSheet("color:white;\n"
"background: rgb(0,0,0,0);")
        self.detailsYouLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.detailsYouLabel.setObjectName("detailsYouLabel")
        self.detailsYandexLabel = QtWidgets.QLabel(self.detailsFrame)
        self.detailsYandexLabel.setGeometry(QtCore.QRect(300, 720, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(8)
        self.detailsYandexLabel.setFont(font)
        self.detailsYandexLabel.setStyleSheet("color:white;\n"
"background: rgb(0,0,0,0);")
        self.detailsYandexLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.detailsYandexLabel.setObjectName("detailsYandexLabel")
        self.detailsSlot2 = QtWidgets.QLabel(self.detailsFrame)
        self.detailsSlot2.setGeometry(QtCore.QRect(0, 170, 401, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(11)
        self.detailsSlot2.setFont(font)
        self.detailsSlot2.setStyleSheet("color:white;\n"
"background: #01A7FF;\n"
"border-radius:20px;\n"
"")
        self.detailsSlot2.setAlignment(QtCore.Qt.AlignCenter)
        self.detailsSlot2.setObjectName("detailsSlot2")
        self.detailsSlot3.raise_()
        self.detailsOpt.raise_()
        self.detailsSlot1.raise_()
        self.detailsYandex.raise_()
        self.detailsSongName.raise_()
        self.detailsArtist.raise_()
        self.detailsYou.raise_()
        self.detailsApple.raise_()
        self.detailsSpotify.raise_()
        self.detailsTopLabel.raise_()
        self.detailsBackBut.raise_()
        self.detailsPlayLabel.raise_()
        self.detailsSpotifyLabel.raise_()
        self.detailsAppleLabel.raise_()
        self.detailsYouLabel.raise_()
        self.detailsYandexLabel.raise_()
        self.detailsSlot2.raise_()
        self.detailsTable.raise_()

        self.retranslateUi(MAIN)
        QtCore.QMetaObject.connectSlotsByName(MAIN)

    def retranslateUi(self, MAIN):
        _translate = QtCore.QCoreApplication.translate
        MAIN.setWindowTitle(_translate("MAIN", "Apollo"))
        self.detailsSongName.setText(_translate("MAIN", "Until The World Goes Cold"))
        self.detailsArtist.setText(_translate("MAIN", "Trivium"))
        self.detailsTopLabel.setText(_translate("MAIN", "Details"))
        self.detailsPlayLabel.setText(_translate("MAIN", "Play with"))
        item = self.detailsTable.horizontalHeaderItem(0)
        item.setText(_translate("MAIN", "User"))
        item = self.detailsTable.horizontalHeaderItem(1)
        item.setText(_translate("MAIN", "Date"))
        item = self.detailsTable.horizontalHeaderItem(2)
        item.setText(_translate("MAIN", "Follow"))
        __sortingEnabled = self.detailsTable.isSortingEnabled()
        self.detailsTable.setSortingEnabled(False)
        item = self.detailsTable.item(0, 0)
        item.setText(_translate("MAIN", "@rick.n.morty"))
        item = self.detailsTable.item(0, 1)
        item.setText(_translate("MAIN", "1 hour ago"))
        item = self.detailsTable.item(0, 2)
        item.setText(_translate("MAIN", "Unfollow"))
        item = self.detailsTable.item(1, 0)
        item.setText(_translate("MAIN", "@xrays7777"))
        item = self.detailsTable.item(1, 1)
        item.setText(_translate("MAIN", "1 hour ago"))
        item = self.detailsTable.item(1, 2)
        item.setText(_translate("MAIN", "Follow"))
        item = self.detailsTable.item(2, 0)
        item.setText(_translate("MAIN", "@cagatay.savasli"))
        item = self.detailsTable.item(2, 1)
        item.setText(_translate("MAIN", "3 hours ago"))
        item = self.detailsTable.item(2, 2)
        item.setText(_translate("MAIN", "Unfollow"))
        item = self.detailsTable.item(3, 0)
        item.setText(_translate("MAIN", "@sangirtioda14"))
        item = self.detailsTable.item(3, 1)
        item.setText(_translate("MAIN", "Yesterday"))
        item = self.detailsTable.item(3, 2)
        item.setText(_translate("MAIN", "Follow"))
        item = self.detailsTable.item(4, 0)
        item.setText(_translate("MAIN", "@katie1"))
        item = self.detailsTable.item(4, 1)
        item.setText(_translate("MAIN", "17.07.2020"))
        item = self.detailsTable.item(4, 2)
        item.setText(_translate("MAIN", "Follow"))
        self.detailsTable.setSortingEnabled(__sortingEnabled)
        self.detailsSpotifyLabel.setText(_translate("MAIN", "Spotify"))
        self.detailsAppleLabel.setText(_translate("MAIN", "Apple\n"
"Music"))
        self.detailsYouLabel.setText(_translate("MAIN", "YouTube"))
        self.detailsYandexLabel.setText(_translate("MAIN", "Yandex\n"
"Music"))
        self.detailsSlot2.setText(_translate("MAIN", "This week"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MAIN = QtWidgets.QWidget()
    ui = Ui_MAIN()
    ui.setupUi(MAIN)
    MAIN.show()
    sys.exit(app.exec_())

