# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'friends.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MAIN(object):
    def setupUi(self, MAIN):
        MAIN.setObjectName("MAIN")
        MAIN.resize(468, 887)
        MAIN.setMinimumSize(QtCore.QSize(468, 887))
        MAIN.setMaximumSize(QtCore.QSize(468, 887))
        self.label = QtWidgets.QLabel(MAIN)
        self.label.setGeometry(QtCore.QRect(0, 0, 463, 901))
        self.label.setMinimumSize(QtCore.QSize(463, 901))
        self.label.setMaximumSize(QtCore.QSize(463, 901))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/phone.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.friendsFrame = QtWidgets.QFrame(MAIN)
        self.friendsFrame.setGeometry(QtCore.QRect(31, 58, 401, 772))
        self.friendsFrame.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0.0738636 #205AFF, stop:0.840909 #1180FF);")
        self.friendsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.friendsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.friendsFrame.setObjectName("friendsFrame")
        self.friend1Slot = QtWidgets.QPushButton(self.friendsFrame)
        self.friend1Slot.setGeometry(QtCore.QRect(15, 80, 371, 101))
        self.friend1Slot.setStyleSheet("background-color: #01A7FF;\n"
"border:0px;\n"
"border-radius:20px;")
        self.friend1Slot.setText("")
        self.friend1Slot.setObjectName("friend1Slot")
        self.friend1Avatar = QtWidgets.QLabel(self.friendsFrame)
        self.friend1Avatar.setGeometry(QtCore.QRect(40, 100, 60, 60))
        self.friend1Avatar.setStyleSheet("background: rgb(0,0,0,0);")
        self.friend1Avatar.setText("")
        self.friend1Avatar.setPixmap(QtGui.QPixmap("img/Friend1.png"))
        self.friend1Avatar.setScaledContents(True)
        self.friend1Avatar.setObjectName("friend1Avatar")
        self.friend1Name = QtWidgets.QLabel(self.friendsFrame)
        self.friend1Name.setGeometry(QtCore.QRect(15, 100, 371, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.friend1Name.setFont(font)
        self.friend1Name.setStyleSheet("background: rgb(0,0,0,0);\n"
"color:white;")
        self.friend1Name.setAlignment(QtCore.Qt.AlignCenter)
        self.friend1Name.setObjectName("friend1Name")
        self.friend1Info = QtWidgets.QLabel(self.friendsFrame)
        self.friend1Info.setGeometry(QtCore.QRect(45, 130, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.friend1Info.setFont(font)
        self.friend1Info.setStyleSheet("background: rgb(0,0,0,0);\n"
"color:black;")
        self.friend1Info.setAlignment(QtCore.Qt.AlignCenter)
        self.friend1Info.setObjectName("friend1Info")
        self.friend1Opt = QtWidgets.QLabel(self.friendsFrame)
        self.friend1Opt.setGeometry(QtCore.QRect(340, 90, 31, 30))
        self.friend1Opt.setStyleSheet("background: rgb(0,0,0,0);")
        self.friend1Opt.setText("")
        self.friend1Opt.setPixmap(QtGui.QPixmap("img/options.png"))
        self.friend1Opt.setScaledContents(True)
        self.friend1Opt.setObjectName("friend1Opt")
        self.friend2Opt = QtWidgets.QLabel(self.friendsFrame)
        self.friend2Opt.setGeometry(QtCore.QRect(335, 210, 31, 30))
        self.friend2Opt.setStyleSheet("background: rgb(0,0,0,0);")
        self.friend2Opt.setText("")
        self.friend2Opt.setPixmap(QtGui.QPixmap("img/options.png"))
        self.friend2Opt.setScaledContents(True)
        self.friend2Opt.setObjectName("friend2Opt")
        self.friend2Info = QtWidgets.QLabel(self.friendsFrame)
        self.friend2Info.setGeometry(QtCore.QRect(40, 250, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.friend2Info.setFont(font)
        self.friend2Info.setStyleSheet("background: rgb(0,0,0,0);\n"
"color:black;")
        self.friend2Info.setAlignment(QtCore.Qt.AlignCenter)
        self.friend2Info.setObjectName("friend2Info")
        self.friend2Name = QtWidgets.QLabel(self.friendsFrame)
        self.friend2Name.setGeometry(QtCore.QRect(10, 220, 371, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.friend2Name.setFont(font)
        self.friend2Name.setStyleSheet("background: rgb(0,0,0,0);\n"
"color:white;")
        self.friend2Name.setAlignment(QtCore.Qt.AlignCenter)
        self.friend2Name.setObjectName("friend2Name")
        self.friend2Avatar = QtWidgets.QLabel(self.friendsFrame)
        self.friend2Avatar.setGeometry(QtCore.QRect(35, 220, 60, 60))
        self.friend2Avatar.setStyleSheet("background: rgb(0,0,0,0);")
        self.friend2Avatar.setText("")
        self.friend2Avatar.setPixmap(QtGui.QPixmap("img/Friend2.png"))
        self.friend2Avatar.setScaledContents(True)
        self.friend2Avatar.setObjectName("friend2Avatar")
        self.friend2Slot = QtWidgets.QPushButton(self.friendsFrame)
        self.friend2Slot.setGeometry(QtCore.QRect(15, 200, 371, 101))
        self.friend2Slot.setStyleSheet("background-color: #01A7FF;\n"
"border:0px;\n"
"border-radius:20px;")
        self.friend2Slot.setText("")
        self.friend2Slot.setObjectName("friend2Slot")
        self.friend3Opt = QtWidgets.QLabel(self.friendsFrame)
        self.friend3Opt.setGeometry(QtCore.QRect(335, 330, 31, 30))
        self.friend3Opt.setStyleSheet("background: rgb(0,0,0,0);")
        self.friend3Opt.setText("")
        self.friend3Opt.setPixmap(QtGui.QPixmap("img/options.png"))
        self.friend3Opt.setScaledContents(True)
        self.friend3Opt.setObjectName("friend3Opt")
        self.friend3Info = QtWidgets.QLabel(self.friendsFrame)
        self.friend3Info.setGeometry(QtCore.QRect(40, 370, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.friend3Info.setFont(font)
        self.friend3Info.setStyleSheet("background: rgb(0,0,0,0);\n"
"color:black;")
        self.friend3Info.setAlignment(QtCore.Qt.AlignCenter)
        self.friend3Info.setObjectName("friend3Info")
        self.friend3Name = QtWidgets.QLabel(self.friendsFrame)
        self.friend3Name.setGeometry(QtCore.QRect(15, 340, 371, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.friend3Name.setFont(font)
        self.friend3Name.setStyleSheet("background: rgb(0,0,0,0);\n"
"color:white;")
        self.friend3Name.setAlignment(QtCore.Qt.AlignCenter)
        self.friend3Name.setObjectName("friend3Name")
        self.friend3Slot = QtWidgets.QPushButton(self.friendsFrame)
        self.friend3Slot.setGeometry(QtCore.QRect(15, 320, 371, 101))
        self.friend3Slot.setStyleSheet("background-color: #01A7FF;\n"
"border:0px;\n"
"border-radius:20px;")
        self.friend3Slot.setText("")
        self.friend3Slot.setObjectName("friend3Slot")
        self.friend3Avatar = QtWidgets.QLabel(self.friendsFrame)
        self.friend3Avatar.setGeometry(QtCore.QRect(30, 340, 60, 60))
        self.friend3Avatar.setStyleSheet("background: rgb(0,0,0,0);")
        self.friend3Avatar.setText("")
        self.friend3Avatar.setPixmap(QtGui.QPixmap("img/friend3.png"))
        self.friend3Avatar.setScaledContents(True)
        self.friend3Avatar.setObjectName("friend3Avatar")
        self.friend4Avatar = QtWidgets.QLabel(self.friendsFrame)
        self.friend4Avatar.setGeometry(QtCore.QRect(30, 460, 60, 60))
        self.friend4Avatar.setStyleSheet("background: rgb(0,0,0,0);")
        self.friend4Avatar.setText("")
        self.friend4Avatar.setPixmap(QtGui.QPixmap("img/Friend4.png"))
        self.friend4Avatar.setScaledContents(True)
        self.friend4Avatar.setObjectName("friend4Avatar")
        self.friend4Opt = QtWidgets.QLabel(self.friendsFrame)
        self.friend4Opt.setGeometry(QtCore.QRect(335, 450, 31, 30))
        self.friend4Opt.setStyleSheet("background: rgb(0,0,0,0);")
        self.friend4Opt.setText("")
        self.friend4Opt.setPixmap(QtGui.QPixmap("img/options.png"))
        self.friend4Opt.setScaledContents(True)
        self.friend4Opt.setObjectName("friend4Opt")
        self.friend4Name = QtWidgets.QLabel(self.friendsFrame)
        self.friend4Name.setGeometry(QtCore.QRect(15, 460, 371, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.friend4Name.setFont(font)
        self.friend4Name.setStyleSheet("background: rgb(0,0,0,0);\n"
"color:white;")
        self.friend4Name.setAlignment(QtCore.Qt.AlignCenter)
        self.friend4Name.setObjectName("friend4Name")
        self.friend4Info = QtWidgets.QLabel(self.friendsFrame)
        self.friend4Info.setGeometry(QtCore.QRect(40, 490, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.friend4Info.setFont(font)
        self.friend4Info.setStyleSheet("background: rgb(0,0,0,0);\n"
"color:black;")
        self.friend4Info.setAlignment(QtCore.Qt.AlignCenter)
        self.friend4Info.setObjectName("friend4Info")
        self.friend4Slot = QtWidgets.QPushButton(self.friendsFrame)
        self.friend4Slot.setGeometry(QtCore.QRect(15, 440, 371, 101))
        self.friend4Slot.setStyleSheet("background-color: #01A7FF;\n"
"border:0px;\n"
"border-radius:20px;")
        self.friend4Slot.setText("")
        self.friend4Slot.setObjectName("friend4Slot")
        self.friendsTopLabel = QtWidgets.QLabel(self.friendsFrame)
        self.friendsTopLabel.setGeometry(QtCore.QRect(0, 30, 401, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(11)
        self.friendsTopLabel.setFont(font)
        self.friendsTopLabel.setStyleSheet("color:white;\n"
"background: rgb(0,0,0,0);")
        self.friendsTopLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.friendsTopLabel.setObjectName("friendsTopLabel")
        self.searchFriendBut = QtWidgets.QLabel(self.friendsFrame)
        self.searchFriendBut.setGeometry(QtCore.QRect(340, 20, 40, 40))
        self.searchFriendBut.setStyleSheet("background: rgb(0,0,0,0);")
        self.searchFriendBut.setText("")
        self.searchFriendBut.setPixmap(QtGui.QPixmap("img/add-friend.png"))
        self.searchFriendBut.setScaledContents(True)
        self.searchFriendBut.setObjectName("searchFriendBut")
        self.friendsBackBut = QtWidgets.QLabel(self.friendsFrame)
        self.friendsBackBut.setGeometry(QtCore.QRect(20, 20, 40, 40))
        self.friendsBackBut.setStyleSheet("background: rgb(0,0,0,0);")
        self.friendsBackBut.setText("")
        self.friendsBackBut.setPixmap(QtGui.QPixmap("img/back.png"))
        self.friendsBackBut.setScaledContents(True)
        self.friendsBackBut.setObjectName("friendsBackBut")
        self.friend4Slot.raise_()
        self.friend3Slot.raise_()
        self.friend3Name.raise_()
        self.friend3Info.raise_()
        self.friend3Opt.raise_()
        self.friend2Slot.raise_()
        self.friend1Slot.raise_()
        self.friend1Avatar.raise_()
        self.friend1Name.raise_()
        self.friend1Info.raise_()
        self.friend1Opt.raise_()
        self.friend2Opt.raise_()
        self.friend2Info.raise_()
        self.friend2Name.raise_()
        self.friend2Avatar.raise_()
        self.friend3Avatar.raise_()
        self.friend4Avatar.raise_()
        self.friend4Opt.raise_()
        self.friend4Name.raise_()
        self.friend4Info.raise_()
        self.friendsTopLabel.raise_()
        self.searchFriendBut.raise_()
        self.friendsBackBut.raise_()

        self.retranslateUi(MAIN)
        QtCore.QMetaObject.connectSlotsByName(MAIN)

    def retranslateUi(self, MAIN):
        _translate = QtCore.QCoreApplication.translate
        MAIN.setWindowTitle(_translate("MAIN", "Apollo"))
        self.friend1Name.setText(_translate("MAIN", "Ayşe Yıldız"))
        self.friend1Info.setText(_translate("MAIN", "Shared 12 songs this week"))
        self.friend2Info.setText(_translate("MAIN", "Shared 20 songs this week"))
        self.friend2Name.setText(_translate("MAIN", "Avni Gül"))
        self.friend3Info.setText(_translate("MAIN", "Shared 7 songs this week"))
        self.friend3Name.setText(_translate("MAIN", "Furkan Tuncay"))
        self.friend4Name.setText(_translate("MAIN", "Maria Moon"))
        self.friend4Info.setText(_translate("MAIN", "Shared 16 songs this week"))
        self.friendsTopLabel.setText(_translate("MAIN", "Friends"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MAIN = QtWidgets.QWidget()
    ui = Ui_MAIN()
    ui.setupUi(MAIN)
    MAIN.show()
    sys.exit(app.exec_())

