# -*- coding: utf-8 -*-

# Created by HoldMyRover Team for OzU Yandex Hackathon

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MAIN(QtWidgets.QWidget):

    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, MAIN):
        MAIN.setObjectName("MAIN")
        MAIN.resize(468, 887)
        MAIN.setMinimumSize(QtCore.QSize(468, 887))
        MAIN.setMaximumSize(QtCore.QSize(468, 887))
        self.label = QtWidgets.QLabel(MAIN)
        self.label.setGeometry(QtCore.QRect(0, 0, 463, 901))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/phone.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.loginFrame = QtWidgets.QFrame(MAIN)
        self.loginFrame.setGeometry(QtCore.QRect(31, 60, 401, 771))
        self.loginFrame.setStyleSheet("background:white;")
        self.loginFrame.setObjectName("widget")
        self.label_2 = QtWidgets.QLabel(self.loginFrame)
        self.label_2.setGeometry(QtCore.QRect(100, 100, 200, 291))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("img/icon.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.loginFrame)
        self.label_3.setGeometry(QtCore.QRect(0, 400, 401, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.username = QtWidgets.QLineEdit(self.loginFrame)
        self.username.setGeometry(QtCore.QRect(80, 500, 270, 30))
        self.username.setStyleSheet("border:1px solid #53bde0;")
        self.username.setAlignment(QtCore.Qt.AlignCenter)
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(self.loginFrame)
        self.password.setGeometry(QtCore.QRect(80, 550, 270, 30))
        self.password.setStyleSheet("border:1px solid #53bde0;")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setAlignment(QtCore.Qt.AlignCenter)
        self.password.setObjectName("password")
        self.loginBut = QtWidgets.QPushButton(self.loginFrame)
        self.loginBut.setGeometry(QtCore.QRect(50, 600, 300, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.loginBut.setFont(font)
        self.loginBut.setStyleSheet("border:0px;\n"
"background:red;\n"
"border-radius:17px;\n"
"color:white;")
        self.loginBut.setObjectName("loginBut")
        self.label_4 = QtWidgets.QLabel(self.loginFrame)
        self.label_4.setGeometry(QtCore.QRect(50, 500, 30, 30))
        self.label_4.setStyleSheet("background:#53bde0;\n"
"border:3px solid #53bde0;")
        self.label_4.setText("")
        self.label_4.setTextFormat(QtCore.Qt.PlainText)
        self.label_4.setPixmap(QtGui.QPixmap("img/user.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.loginFrame)
        self.label_5.setGeometry(QtCore.QRect(50, 550, 30, 30))
        self.label_5.setStyleSheet("background:#53bde0;\n"
"border:3px solid #53bde0;")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("img/password.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.loginFrame)
        self.label_6.setGeometry(QtCore.QRect(90, 640, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.loginFrame)
        self.label_7.setGeometry(QtCore.QRect(240, 638, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setUnderline(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.loginFrame)
        self.label_8.setGeometry(QtCore.QRect(195, 430, 71, 31))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("img/yandex_PNG20.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")

        self.homeFrame = QtWidgets.QFrame(MAIN)
        self.homeFrame.setGeometry(QtCore.QRect(31, 58, 401, 772))
        self.homeFrame.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0.0738636 #205AFF, stop:0.840909 #1180FF);")
        self.homeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.homeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.homeFrame.setObjectName("homeFrame")
        self.settingsBut = QtWidgets.QPushButton(self.homeFrame)
        self.settingsBut.setGeometry(QtCore.QRect(20, 20, 40, 40))
        self.settingsBut.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.settingsBut.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsBut.setIcon(icon)
        self.settingsBut.setIconSize(QtCore.QSize(30, 30))
        self.settingsBut.setObjectName("settingsBut")
        self.profileBut = QtWidgets.QPushButton(self.homeFrame)
        self.profileBut.setGeometry(QtCore.QRect(340, 20, 40, 40))
        self.profileBut.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.profileBut.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.profileBut.setIcon(icon1)
        self.profileBut.setIconSize(QtCore.QSize(30, 30))
        self.profileBut.setObjectName("profileBut")
        self.musicBut = QtWidgets.QPushButton(self.homeFrame)
        self.musicBut.setGeometry(QtCore.QRect(150, 670, 100, 100))
        self.musicBut.setStyleSheet("background-color: #66CCFF;\n"
"border:0px;\n"
"border-radius:50px;")
        self.musicBut.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/sign.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.musicBut.setIcon(icon2)
        self.musicBut.setIconSize(QtCore.QSize(60, 60))
        self.musicBut.setObjectName("musicBut")
        self.botBackLabel = QtWidgets.QLabel(self.homeFrame)
        self.botBackLabel.setGeometry(QtCore.QRect(19, 700, 371, 51))
        self.botBackLabel.setStyleSheet("background-color: #01A7FF;\n"
"border:0px;\n"
"border-radius:20px;")
        self.botBackLabel.setText("")
        self.botBackLabel.setObjectName("botBackLabel")
        self.worldBut = QtWidgets.QPushButton(self.homeFrame)
        self.worldBut.setGeometry(QtCore.QRect(340, 705, 40, 40))
        self.worldBut.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.worldBut.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/sustainability.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.worldBut.setIcon(icon3)
        self.worldBut.setIconSize(QtCore.QSize(35, 35))
        self.worldBut.setObjectName("worldBut")
        self.likeBut = QtWidgets.QPushButton(self.homeFrame)
        self.likeBut.setGeometry(QtCore.QRect(30, 705, 40, 40))
        self.likeBut.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.likeBut.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("img/liked.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.likeBut.setIcon(icon4)
        self.likeBut.setIconSize(QtCore.QSize(35, 35))
        self.likeBut.setObjectName("likeBut")
        self.mapLabel = QtWidgets.QLabel(self.homeFrame)
        self.mapLabel.setGeometry(QtCore.QRect(0, 120, 401, 200))
        self.mapLabel.setText("")
        self.mapLabel.setPixmap(QtGui.QPixmap("img/gps.png"))
        self.mapLabel.setScaledContents(True)
        self.mapLabel.setObjectName("mapLabel")
        self.friendsBut = QtWidgets.QPushButton(self.homeFrame)
        self.friendsBut.setGeometry(QtCore.QRect(90, 705, 40, 40))
        self.friendsBut.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.friendsBut.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("img/friend.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.friendsBut.setIcon(icon5)
        self.friendsBut.setIconSize(QtCore.QSize(35, 35))
        self.friendsBut.setObjectName("friendsBut")
        self.routeBut = QtWidgets.QPushButton(self.homeFrame)
        self.routeBut.setGeometry(QtCore.QRect(270, 705, 40, 40))
        self.routeBut.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.routeBut.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("img/Route.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.routeBut.setIcon(icon6)
        self.routeBut.setIconSize(QtCore.QSize(35, 35))
        self.routeBut.setObjectName("routeBut")
        self.songNameList = QtWidgets.QListWidget(self.homeFrame)
        self.songNameList.setGeometry(QtCore.QRect(0, 340, 321, 241))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(11)
        self.songNameList.setFont(font)
        self.songNameList.setStyleSheet("background:white;\n"
"color:gray;\n"
"border:0px;")
        self.songNameList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.songNameList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.songNameList.setIconSize(QtCore.QSize(15, 15))
        self.songNameList.setMovement(QtWidgets.QListView.Static)
        self.songNameList.setFlow(QtWidgets.QListView.TopToBottom)
        self.songNameList.setProperty("isWrapping", False)
        self.songNameList.setViewMode(QtWidgets.QListView.ListMode)
        self.songNameList.setUniformItemSizes(False)
        self.songNameList.setWordWrap(False)
        self.songNameList.setSelectionRectVisible(False)
        self.songNameList.setObjectName("songNameList")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.songNameList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.songNameList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.songNameList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.songNameList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.songNameList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.songNameList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.songNameList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.songNameList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.songNameList.addItem(item)
        self.songCountList = QtWidgets.QListWidget(self.homeFrame)
        self.songCountList.setGeometry(QtCore.QRect(321, 340, 80, 241))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(11)
        self.songCountList.setFont(font)
        self.songCountList.setStyleSheet("background:white;\n"
"color:green;\n"
"border:0px;")
        self.songCountList.setIconSize(QtCore.QSize(15, 15))
        self.songCountList.setMovement(QtWidgets.QListView.Static)
        self.songCountList.setFlow(QtWidgets.QListView.TopToBottom)
        self.songCountList.setProperty("isWrapping", False)
        self.songCountList.setViewMode(QtWidgets.QListView.ListMode)
        self.songCountList.setUniformItemSizes(False)
        self.songCountList.setWordWrap(False)
        self.songCountList.setSelectionRectVisible(False)
        self.songCountList.setObjectName("songCountList")
        item = QtWidgets.QListWidgetItem()
        self.songCountList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.songCountList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.songCountList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.songCountList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.songCountList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.songCountList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.songCountList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.songCountList.addItem(item)
        self.locLabel = QtWidgets.QLabel(self.homeFrame)
        self.locLabel.setGeometry(QtCore.QRect(0, 80, 401, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.locLabel.setFont(font)
        self.locLabel.setStyleSheet("color:white;\n"
"background:#1180FF;")
        self.locLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.locLabel.setObjectName("locLabel")
        self.weekBackLabel = QtWidgets.QLabel(self.homeFrame)
        self.weekBackLabel.setGeometry(QtCore.QRect(20, 600, 371, 61))
        self.weekBackLabel.setStyleSheet("background: #01A7FF;\n"
"border-radius:15px;")
        self.weekBackLabel.setText("")
        self.weekBackLabel.setObjectName("weekBackLabel")
        self.songWeekLabel = QtWidgets.QLabel(self.homeFrame)
        self.songWeekLabel.setGeometry(QtCore.QRect(20, 600, 371, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.songWeekLabel.setFont(font)
        self.songWeekLabel.setStyleSheet("background: rgb(0,0,0,0);\n"
"color:black;")
        self.songWeekLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.songWeekLabel.setObjectName("songWeekLabel")
        self.weekSongLabel = QtWidgets.QLabel(self.homeFrame)
        self.weekSongLabel.setGeometry(QtCore.QRect(20, 630, 371, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.weekSongLabel.setFont(font)
        self.weekSongLabel.setStyleSheet("background: rgb(0,0,0,0);\n"
"color:#d3d4e0;")
        self.weekSongLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.weekSongLabel.setObjectName("weekSongLabel")
        self.settingsBut.raise_()
        self.profileBut.raise_()
        self.botBackLabel.raise_()
        self.worldBut.raise_()
        self.mapLabel.raise_()
        self.routeBut.raise_()
        self.songNameList.raise_()
        self.likeBut.raise_()
        self.friendsBut.raise_()
        self.songCountList.raise_()
        self.locLabel.raise_()
        self.weekBackLabel.raise_()
        self.musicBut.raise_()
        self.songWeekLabel.raise_()
        self.weekSongLabel.raise_()

        self.historyFrame = QtWidgets.QFrame(MAIN)
        self.historyFrame.setGeometry(QtCore.QRect(31, 58, 401, 772))
        self.historyFrame.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0.0738636 #205AFF, stop:0.840909 #1180FF);")
        self.historyFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.historyFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.historyFrame.setObjectName("historyFrame")
        self.historyBackBut = QtWidgets.QPushButton(self.historyFrame)
        self.historyBackBut.setGeometry(QtCore.QRect(20, 20, 40, 40))
        self.historyBackBut.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.historyBackBut.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.historyBackBut.setIcon(icon)
        self.historyBackBut.setIconSize(QtCore.QSize(30, 30))
        self.historyBackBut.setObjectName("historyBackBut")
        self.historyTopLabel = QtWidgets.QLabel(self.historyFrame)
        self.historyTopLabel.setGeometry(QtCore.QRect(0, 30, 401, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        font.setWeight(75)
        self.historyTopLabel.setFont(font)
        self.historyTopLabel.setStyleSheet("background: rgb(0,0,0,0);\n"
"color:white;")
        self.historyTopLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.historyTopLabel.setObjectName("historyTopLabel")
        self.historyLineEdit = QtWidgets.QLineEdit(self.historyFrame)
        self.historyLineEdit.setGeometry(QtCore.QRect(14, 80, 371, 41))
        self.historyLineEdit.setStyleSheet("background:white;\n"
"border-radius:10px;")
        self.historyLineEdit.setMaxLength(32766)
        self.historyLineEdit.setObjectName("historyLineEdit")
        self.historySearchBut = QtWidgets.QPushButton(self.historyFrame)
        self.historySearchBut.setGeometry(QtCore.QRect(343, 85, 31, 28))
        self.historySearchBut.setStyleSheet("background:white;\n"
"border:0px;")
        self.historySearchBut.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.historySearchBut.setIcon(icon1)
        self.historySearchBut.setObjectName("historySearchBut")
        self.historySongList = QtWidgets.QListWidget(self.historyFrame)
        self.historySongList.setGeometry(QtCore.QRect(0, 140, 401, 631))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(11)
        self.historySongList.setFont(font)
        self.historySongList.setStyleSheet("background:white;\n"
"color:gray;\n"
"border:0px;")
        self.historySongList.setObjectName("historySongList")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.historySongList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.historySongList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.historySongList.addItem(item)
        self.historyTopLabel.raise_()
        self.historyLineEdit.raise_()
        self.historySearchBut.raise_()
        self.historySongList.raise_()
        self.historyBackBut.raise_()

        self.friendsFrame = QtWidgets.QFrame(MAIN)
        self.friendsFrame.setGeometry(QtCore.QRect(31, 58, 401, 772))
        self.friendsFrame.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0.0738636 #205AFF, stop:0.840909 #1180FF);")
        self.friendsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.friendsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.friendsFrame.setObjectName("friendsFrame")
        self.friend1Slot = QtWidgets.QPushButton(self.friendsFrame)
        self.friend1Slot.setGeometry(QtCore.QRect(15, 80, 371, 101))
        self.friend1Slot.setStyleSheet("background-color: #01A7FF;\n"
"border:0px;\n"
"border-radius:20px;")
        self.friend1Slot.setText("")
        self.friend1Slot.setObjectName("friend1Slot")
        self.friend1Avatar = QtWidgets.QLabel(self.friendsFrame)
        self.friend1Avatar.setGeometry(QtCore.QRect(40, 100, 60, 60))
        self.friend1Avatar.setStyleSheet("background: rgb(0,0,0,0);")
        self.friend1Avatar.setText("")
        self.friend1Avatar.setPixmap(QtGui.QPixmap("img/Friend1.png"))
        self.friend1Avatar.setScaledContents(True)
        self.friend1Avatar.setObjectName("friend1Avatar")
        self.friend1Name = QtWidgets.QLabel(self.friendsFrame)
        self.friend1Name.setGeometry(QtCore.QRect(15, 100, 371, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.friend1Name.setFont(font)
        self.friend1Name.setStyleSheet("background: rgb(0,0,0,0);\n"
"color:white;")
        self.friend1Name.setAlignment(QtCore.Qt.AlignCenter)
        self.friend1Name.setObjectName("friend1Name")
        self.friend1Info = QtWidgets.QLabel(self.friendsFrame)
        self.friend1Info.setGeometry(QtCore.QRect(45, 130, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.friend1Info.setFont(font)
        self.friend1Info.setStyleSheet("background: rgb(0,0,0,0);\n"
"color:black;")
        self.friend1Info.setAlignment(QtCore.Qt.AlignCenter)
        self.friend1Info.setObjectName("friend1Info")
        self.friend1Opt = QtWidgets.QLabel(self.friendsFrame)
        self.friend1Opt.setGeometry(QtCore.QRect(340, 90, 31, 30))
        self.friend1Opt.setStyleSheet("background: rgb(0,0,0,0);")
        self.friend1Opt.setText("")
        self.friend1Opt.setPixmap(QtGui.QPixmap("img/options.png"))
        self.friend1Opt.setScaledContents(True)
        self.friend1Opt.setObjectName("friend1Opt")
        self.friend2Opt = QtWidgets.QLabel(self.friendsFrame)
        self.friend2Opt.setGeometry(QtCore.QRect(335, 210, 31, 30))
        self.friend2Opt.setStyleSheet("background: rgb(0,0,0,0);")
        self.friend2Opt.setText("")
        self.friend2Opt.setPixmap(QtGui.QPixmap("img/options.png"))
        self.friend2Opt.setScaledContents(True)
        self.friend2Opt.setObjectName("friend2Opt")
        self.friend2Info = QtWidgets.QLabel(self.friendsFrame)
        self.friend2Info.setGeometry(QtCore.QRect(40, 250, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.friend2Info.setFont(font)
        self.friend2Info.setStyleSheet("background: rgb(0,0,0,0);\n"
"color:black;")
        self.friend2Info.setAlignment(QtCore.Qt.AlignCenter)
        self.friend2Info.setObjectName("friend2Info")
        self.friend2Name = QtWidgets.QLabel(self.friendsFrame)
        self.friend2Name.setGeometry(QtCore.QRect(10, 220, 371, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.friend2Name.setFont(font)
        self.friend2Name.setStyleSheet("background: rgb(0,0,0,0);\n"
"color:white;")
        self.friend2Name.setAlignment(QtCore.Qt.AlignCenter)
        self.friend2Name.setObjectName("friend2Name")
        self.friend2Avatar = QtWidgets.QLabel(self.friendsFrame)
        self.friend2Avatar.setGeometry(QtCore.QRect(35, 220, 60, 60))
        self.friend2Avatar.setStyleSheet("background: rgb(0,0,0,0);")
        self.friend2Avatar.setText("")
        self.friend2Avatar.setPixmap(QtGui.QPixmap("img/Friend2.png"))
        self.friend2Avatar.setScaledContents(True)
        self.friend2Avatar.setObjectName("friend2Avatar")
        self.friend2Slot = QtWidgets.QPushButton(self.friendsFrame)
        self.friend2Slot.setGeometry(QtCore.QRect(15, 200, 371, 101))
        self.friend2Slot.setStyleSheet("background-color: #01A7FF;\n"
"border:0px;\n"
"border-radius:20px;")
        self.friend2Slot.setText("")
        self.friend2Slot.setObjectName("friend2Slot")
        self.friend3Opt = QtWidgets.QLabel(self.friendsFrame)
        self.friend3Opt.setGeometry(QtCore.QRect(335, 330, 31, 30))
        self.friend3Opt.setStyleSheet("background: rgb(0,0,0,0);")
        self.friend3Opt.setText("")
        self.friend3Opt.setPixmap(QtGui.QPixmap("img/options.png"))
        self.friend3Opt.setScaledContents(True)
        self.friend3Opt.setObjectName("friend3Opt")
        self.friend3Info = QtWidgets.QLabel(self.friendsFrame)
        self.friend3Info.setGeometry(QtCore.QRect(40, 370, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.friend3Info.setFont(font)
        self.friend3Info.setStyleSheet("background: rgb(0,0,0,0);\n"
"color:black;")
        self.friend3Info.setAlignment(QtCore.Qt.AlignCenter)
        self.friend3Info.setObjectName("friend3Info")
        self.friend3Name = QtWidgets.QLabel(self.friendsFrame)
        self.friend3Name.setGeometry(QtCore.QRect(15, 340, 371, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.friend3Name.setFont(font)
        self.friend3Name.setStyleSheet("background: rgb(0,0,0,0);\n"
"color:white;")
        self.friend3Name.setAlignment(QtCore.Qt.AlignCenter)
        self.friend3Name.setObjectName("friend3Name")
        self.friend3Slot = QtWidgets.QPushButton(self.friendsFrame)
        self.friend3Slot.setGeometry(QtCore.QRect(15, 320, 371, 101))
        self.friend3Slot.setStyleSheet("background-color: #01A7FF;\n"
"border:0px;\n"
"border-radius:20px;")
        self.friend3Slot.setText("")
        self.friend3Slot.setObjectName("friend3Slot")
        self.friend3Avatar = QtWidgets.QLabel(self.friendsFrame)
        self.friend3Avatar.setGeometry(QtCore.QRect(30, 340, 60, 60))
        self.friend3Avatar.setStyleSheet("background: rgb(0,0,0,0);")
        self.friend3Avatar.setText("")
        self.friend3Avatar.setPixmap(QtGui.QPixmap("img/friend3.png"))
        self.friend3Avatar.setScaledContents(True)
        self.friend3Avatar.setObjectName("friend3Avatar")
        self.friend4Avatar = QtWidgets.QLabel(self.friendsFrame)
        self.friend4Avatar.setGeometry(QtCore.QRect(30, 460, 60, 60))
        self.friend4Avatar.setStyleSheet("background: rgb(0,0,0,0);")
        self.friend4Avatar.setText("")
        self.friend4Avatar.setPixmap(QtGui.QPixmap("img/Friend4.png"))
        self.friend4Avatar.setScaledContents(True)
        self.friend4Avatar.setObjectName("friend4Avatar")
        self.friend4Opt = QtWidgets.QLabel(self.friendsFrame)
        self.friend4Opt.setGeometry(QtCore.QRect(335, 450, 31, 30))
        self.friend4Opt.setStyleSheet("background: rgb(0,0,0,0);")
        self.friend4Opt.setText("")
        self.friend4Opt.setPixmap(QtGui.QPixmap("img/options.png"))
        self.friend4Opt.setScaledContents(True)
        self.friend4Opt.setObjectName("friend4Opt")
        self.friend4Name = QtWidgets.QLabel(self.friendsFrame)
        self.friend4Name.setGeometry(QtCore.QRect(15, 460, 371, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.friend4Name.setFont(font)
        self.friend4Name.setStyleSheet("background: rgb(0,0,0,0);\n"
"color:white;")
        self.friend4Name.setAlignment(QtCore.Qt.AlignCenter)
        self.friend4Name.setObjectName("friend4Name")
        self.friend4Info = QtWidgets.QLabel(self.friendsFrame)
        self.friend4Info.setGeometry(QtCore.QRect(40, 490, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.friend4Info.setFont(font)
        self.friend4Info.setStyleSheet("background: rgb(0,0,0,0);\n"
"color:black;")
        self.friend4Info.setAlignment(QtCore.Qt.AlignCenter)
        self.friend4Info.setObjectName("friend4Info")
        self.friend4Slot = QtWidgets.QPushButton(self.friendsFrame)
        self.friend4Slot.setGeometry(QtCore.QRect(15, 440, 371, 101))
        self.friend4Slot.setStyleSheet("background-color: #01A7FF;\n"
"border:0px;\n"
"border-radius:20px;")
        self.friend4Slot.setText("")
        self.friend4Slot.setObjectName("friend4Slot")
        self.friendsTopLabel = QtWidgets.QLabel(self.friendsFrame)
        self.friendsTopLabel.setGeometry(QtCore.QRect(0, 30, 401, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.friendsTopLabel.setFont(font)
        self.friendsTopLabel.setStyleSheet("color:white;\n"
"background: rgb(0,0,0,0);")
        self.friendsTopLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.friendsTopLabel.setObjectName("friendsTopLabel")
        self.searchFriendBut = QtWidgets.QLabel(self.friendsFrame)
        self.searchFriendBut.setGeometry(QtCore.QRect(340, 20, 40, 40))
        self.searchFriendBut.setStyleSheet("background: rgb(0,0,0,0);")
        self.searchFriendBut.setText("")
        self.searchFriendBut.setPixmap(QtGui.QPixmap("img/add-friend.png"))
        self.searchFriendBut.setScaledContents(True)
        self.searchFriendBut.setObjectName("searchFriendBut")
        self.friendsBackBut = QtWidgets.QPushButton(self.friendsFrame)
        self.friendsBackBut.setGeometry(QtCore.QRect(20, 20, 40, 40))
        self.friendsBackBut.setStyleSheet("background: rgb(0,0,0,0);")
        self.friendsBackBut.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.friendsBackBut.setIcon(icon)
        self.friendsBackBut.setIconSize(QtCore.QSize(40, 40))
        self.friendsBackBut.setObjectName("friendsBackBut")
        self.friend4Slot.raise_()
        self.friend3Slot.raise_()
        self.friend3Name.raise_()
        self.friend3Info.raise_()
        self.friend3Opt.raise_()
        self.friend2Slot.raise_()
        self.friend1Slot.raise_()
        self.friend1Avatar.raise_()
        self.friend1Name.raise_()
        self.friend1Info.raise_()
        self.friend1Opt.raise_()
        self.friend2Opt.raise_()
        self.friend2Info.raise_()
        self.friend2Name.raise_()
        self.friend2Avatar.raise_()
        self.friend3Avatar.raise_()
        self.friend4Avatar.raise_()
        self.friend4Opt.raise_()
        self.friend4Name.raise_()
        self.friend4Info.raise_()
        self.friendsTopLabel.raise_()
        self.searchFriendBut.raise_()
        self.friendsBackBut.raise_()

        self.worldFrame = QtWidgets.QFrame(MAIN)
        self.worldFrame.setGeometry(QtCore.QRect(31, 58, 401, 772))
        self.worldFrame.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0.0738636 #205AFF, stop:0.840909 #1180FF);")
        self.worldFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.worldFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.worldFrame.setObjectName("worldFrame")
        self.worldBackBut = QtWidgets.QPushButton(self.worldFrame)
        self.worldBackBut.setGeometry(QtCore.QRect(20, 20, 40, 40))
        self.worldBackBut.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.worldBackBut.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.worldBackBut.setIcon(icon)
        self.worldBackBut.setIconSize(QtCore.QSize(30, 30))
        self.worldBackBut.setObjectName("worldBackBut")
        self.worldTopLabel = QtWidgets.QLabel(self.worldFrame)
        self.worldTopLabel.setGeometry(QtCore.QRect(0, 30, 401, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.worldTopLabel.setFont(font)
        self.worldTopLabel.setStyleSheet("background: rgb(0,0,0,0);\n"
"color:white;")
        self.worldTopLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.worldTopLabel.setObjectName("worldTopLabel")
        self.worldImage = QtWidgets.QLabel(self.worldFrame)
        self.worldImage.setGeometry(QtCore.QRect(0, 70, 401, 701))
        self.worldImage.setText("")
        self.worldImage.setPixmap(QtGui.QPixmap("img/gps2.png"))
        self.worldImage.setScaledContents(True)
        self.worldImage.setObjectName("worldImage")
        self.worldTopLabel.raise_()
        self.worldBackBut.raise_()
        self.worldImage.raise_()

        self.routeFrame = QtWidgets.QFrame(MAIN)
        self.routeFrame.setGeometry(QtCore.QRect(31, 58, 401, 772))
        self.routeFrame.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0.0738636 #205AFF, stop:0.840909 #1180FF);")
        self.routeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.routeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.routeFrame.setObjectName("routeFrame")
        self.routeBackBut = QtWidgets.QPushButton(self.routeFrame)
        self.routeBackBut.setGeometry(QtCore.QRect(20, 20, 40, 40))
        self.routeBackBut.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.routeBackBut.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.routeBackBut.setIcon(icon)
        self.routeBackBut.setIconSize(QtCore.QSize(30, 30))
        self.routeBackBut.setObjectName("routeBackBut")
        self.routeTopLabel = QtWidgets.QLabel(self.routeFrame)
        self.routeTopLabel.setGeometry(QtCore.QRect(0, 30, 401, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.routeTopLabel.setFont(font)
        self.routeTopLabel.setStyleSheet("background: rgb(0,0,0,0);\n"
"color:white;")
        self.routeTopLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.routeTopLabel.setObjectName("routeTopLabel")
        self.routeMap = QtWidgets.QLabel(self.routeFrame)
        self.routeMap.setGeometry(QtCore.QRect(0, 70, 401, 322))
        self.routeMap.setText("")
        self.routeMap.setPixmap(QtGui.QPixmap("img/gps3.png"))
        self.routeMap.setScaledContents(True)
        self.routeMap.setObjectName("routeMap")
        self.routeSongList = QtWidgets.QListWidget(self.routeFrame)
        self.routeSongList.setGeometry(QtCore.QRect(0, 444, 401, 328))
        self.routeSongList.setStyleSheet("background:white;\n"
"color:gray;\n"
"border:0px;")
        self.routeSongList.setObjectName("routeSongList")
        self.routeSongList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.routeSongList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(11)
        self.routeSongList.setFont(font)
        self.comboBox = QtWidgets.QComboBox(self.routeFrame)
        self.comboBox.setGeometry(QtCore.QRect(10, 400, 381, 31))
        self.comboBox.setStyleSheet("background:#01A7FF;")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.routeTopLabel.raise_()
        self.routeBackBut.raise_()
        self.routeMap.raise_()
        self.routeSongList.raise_()
        self.comboBox.raise_()

        self.shareFrame = QtWidgets.QFrame(MAIN)
        self.shareFrame.setGeometry(QtCore.QRect(31, 58, 401, 772))
        self.shareFrame.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0.0738636 #205AFF, stop:0.840909 #1180FF);")
        self.shareFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.shareFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.shareFrame.setObjectName("shareFrame")
        self.shareBackBut = QtWidgets.QPushButton(self.shareFrame)
        self.shareBackBut.setGeometry(QtCore.QRect(20, 20, 40, 40))
        self.shareBackBut.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.shareBackBut.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shareBackBut.setIcon(icon)
        self.shareBackBut.setIconSize(QtCore.QSize(30, 30))
        self.shareBackBut.setObjectName("shareBackBut")
        self.shareTopLabel = QtWidgets.QLabel(self.shareFrame)
        self.shareTopLabel.setGeometry(QtCore.QRect(0, 30, 401, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.shareTopLabel.setFont(font)
        self.shareTopLabel.setStyleSheet("background: rgb(0,0,0,0);\n"
"color:white;")
        self.shareTopLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.shareTopLabel.setObjectName("shareTopLabel")
        self.shareMap = QtWidgets.QLabel(self.shareFrame)
        self.shareMap.setGeometry(QtCore.QRect(0, 70, 401, 201))
        self.shareMap.setText("")
        self.shareMap.setPixmap(QtGui.QPixmap("img/gps.png"))
        self.shareMap.setScaledContents(True)
        self.shareMap.setObjectName("shareMap")
        self.shareSongList = QtWidgets.QListWidget(self.shareFrame)
        self.shareSongList.setGeometry(QtCore.QRect(0, 341, 401, 361))
        self.shareSongList.setStyleSheet("background:white;\n"
"color:gray;\n"
"border:0px;")
        self.shareSongList.setObjectName("shareSongList")
        self.shareSongList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.shareSongList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(11)
        self.shareSongList.setFont(font)
        self.shareSearchBox = QtWidgets.QLineEdit(self.shareFrame)
        self.shareSearchBox.setGeometry(QtCore.QRect(14, 280, 371, 41))
        self.shareSearchBox.setStyleSheet("background:white;\n"
"border-radius:10px;")
        self.shareSearchBox.setObjectName("shareSearchBox")
        self.shareSearchButton = QtWidgets.QPushButton(self.shareFrame)
        self.shareSearchButton.setGeometry(QtCore.QRect(350, 287, 31, 28))
        self.shareSearchButton.setStyleSheet("background: rgb(0,0,0,0);")
        self.shareSearchButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shareSearchButton.setIcon(icon1)
        self.shareSearchButton.setObjectName("shareSearchButton")
        self.shareShareBut = QtWidgets.QPushButton(self.shareFrame)
        self.shareShareBut.setGeometry(QtCore.QRect(10, 710, 381, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.shareShareBut.setFont(font)
        self.shareShareBut.setStyleSheet("background:#61d47e;\n"
"border:0px;\n"
"border-radius:20px;\n"
"color:white;")
        self.shareShareBut.setObjectName("shareShareBut")
        self.shareTopLabel.raise_()
        self.shareBackBut.raise_()
        self.shareMap.raise_()
        self.shareSongList.raise_()
        self.shareSearchBox.raise_()
        self.shareSearchButton.raise_()
        self.shareShareBut.raise_()

        self.successFrame = QtWidgets.QFrame(self.shareFrame)
        self.successFrame.setGeometry(QtCore.QRect(95, 240, 211, 211))
        self.successFrame.setStyleSheet("background:#092f6e;\n"
"border-radius:25px;")
        self.successFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.successFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.successFrame.setObjectName("successFrame")
        self.successImg = QtWidgets.QLabel(self.successFrame)
        self.successImg.setGeometry(QtCore.QRect(30, 30, 150, 150))
        self.successImg.setText("")
        self.successImg.setPixmap(QtGui.QPixmap("img/tick.png"))
        self.successImg.setScaledContents(True)
        self.successImg.setObjectName("successImg")
        self.successLabel = QtWidgets.QLabel(self.successFrame)
        self.successLabel.setGeometry(QtCore.QRect(50, 180, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.successLabel.setFont(font)
        self.successLabel.setObjectName("successLabel")
        self.successLabel.setStyleSheet("color:white;")
        self.successBackBut = QtWidgets.QPushButton(self.successFrame)
        self.successBackBut.setGeometry(QtCore.QRect(170, 10, 25, 25))
        self.successBackBut.setStyleSheet("color:white;\n"
"background:red;\n"
"border-radius:12px;")
        self.successBackBut.setText("")
        self.successBackBut.setObjectName("successBackBut")

        self.detailsFrame = QtWidgets.QFrame(MAIN)
        self.detailsFrame.setGeometry(QtCore.QRect(31, 58, 401, 772))
        self.detailsFrame.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0.0738636 #205AFF, stop:0.840909 #1180FF);")
        self.detailsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.detailsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.detailsFrame.setObjectName("detailsFrame")
        self.detailsSlot1 = QtWidgets.QPushButton(self.detailsFrame)
        self.detailsSlot1.setGeometry(QtCore.QRect(15, 80, 371, 61))
        self.detailsSlot1.setStyleSheet("background-color: #01A7FF;\n"
"border:0px;\n"
"border-radius:20px;")
        self.detailsSlot1.setText("")
        self.detailsSlot1.setObjectName("detailsSlot1")
        self.detailsYandex = QtWidgets.QLabel(self.detailsFrame)
        self.detailsYandex.setGeometry(QtCore.QRect(300, 660, 60, 60))
        self.detailsYandex.setStyleSheet("background: rgb(0,0,0,0);")
        self.detailsYandex.setText("")
        self.detailsYandex.setPixmap(QtGui.QPixmap("img/yandexmus.png"))
        self.detailsYandex.setScaledContents(True)
        self.detailsYandex.setObjectName("detailsYandex")
        self.detailsSongName = QtWidgets.QLabel(self.detailsFrame)
        self.detailsSongName.setGeometry(QtCore.QRect(15, 90, 371, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.detailsSongName.setFont(font)
        self.detailsSongName.setStyleSheet("background: rgb(0,0,0,0);")
        self.detailsSongName.setAlignment(QtCore.Qt.AlignCenter)
        self.detailsSongName.setObjectName("detailsSongName")
        self.detailsArtist = QtWidgets.QLabel(self.detailsFrame)
        self.detailsArtist.setGeometry(QtCore.QRect(10, 110, 371, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.detailsArtist.setFont(font)
        self.detailsArtist.setStyleSheet("background: rgb(0,0,0,0);\n"
"color:#d3d4e0;")
        self.detailsArtist.setAlignment(QtCore.Qt.AlignCenter)
        self.detailsArtist.setObjectName("detailsArtist")
        self.detailsYou = QtWidgets.QLabel(self.detailsFrame)
        self.detailsYou.setGeometry(QtCore.QRect(213, 660, 60, 60))
        self.detailsYou.setStyleSheet("background: rgb(0,0,0,0);")
        self.detailsYou.setText("")
        self.detailsYou.setPixmap(QtGui.QPixmap("img/youtub.png"))
        self.detailsYou.setScaledContents(True)
        self.detailsYou.setObjectName("detailsYou")
        self.detailsOpt = QtWidgets.QLabel(self.detailsFrame)
        self.detailsOpt.setGeometry(QtCore.QRect(335, 627, 31, 30))
        self.detailsOpt.setStyleSheet("background: rgb(0,0,0,0);")
        self.detailsOpt.setText("")
        self.detailsOpt.setPixmap(QtGui.QPixmap("img/options.png"))
        self.detailsOpt.setScaledContents(True)
        self.detailsOpt.setObjectName("detailsOpt")
        self.detailsApple = QtWidgets.QLabel(self.detailsFrame)
        self.detailsApple.setGeometry(QtCore.QRect(127, 660, 65, 65))
        self.detailsApple.setStyleSheet("background: rgb(0,0,0,0);")
        self.detailsApple.setText("")
        self.detailsApple.setPixmap(QtGui.QPixmap("img/apple.png"))
        self.detailsApple.setScaledContents(True)
        self.detailsApple.setObjectName("detailsApple")
        self.detailsSpotify = QtWidgets.QLabel(self.detailsFrame)
        self.detailsSpotify.setGeometry(QtCore.QRect(41, 660, 60, 60))
        self.detailsSpotify.setStyleSheet("background: rgb(0,0,0,0);")
        self.detailsSpotify.setText("")
        self.detailsSpotify.setPixmap(QtGui.QPixmap("img/spotify.png"))
        self.detailsSpotify.setScaledContents(True)
        self.detailsSpotify.setObjectName("detailsSpotify")
        self.detailsSlot3 = QtWidgets.QPushButton(self.detailsFrame)
        self.detailsSlot3.setGeometry(QtCore.QRect(15, 620, 371, 141))
        self.detailsSlot3.setStyleSheet("background-color: #01A7FF;\n"
"border:0px;\n"
"border-radius:20px;")
        self.detailsSlot3.setText("")
        self.detailsSlot3.setObjectName("detailsSlot3")
        self.detailsTopLabel = QtWidgets.QLabel(self.detailsFrame)
        self.detailsTopLabel.setGeometry(QtCore.QRect(0, 30, 401, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(11)
        self.detailsTopLabel.setFont(font)
        self.detailsTopLabel.setStyleSheet("color:white;\n"
"background: rgb(0,0,0,0);")
        self.detailsTopLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.detailsTopLabel.setObjectName("detailsTopLabel")
        self.detailsBackBut = QtWidgets.QPushButton(self.detailsFrame)
        self.detailsBackBut.setGeometry(QtCore.QRect(20, 20, 40, 40))
        self.detailsBackBut.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.detailsBackBut.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.detailsBackBut.setIcon(icon)
        self.detailsBackBut.setIconSize(QtCore.QSize(30, 30))
        self.detailsBackBut.setObjectName("detailsBackBut")
        self.detailsPlayLabel = QtWidgets.QLabel(self.detailsFrame)
        self.detailsPlayLabel.setGeometry(QtCore.QRect(40, 630, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.detailsPlayLabel.setFont(font)
        self.detailsPlayLabel.setStyleSheet("background: rgb(0,0,0,0);\n"
"color:black;")
        self.detailsPlayLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.detailsPlayLabel.setObjectName("detailsPlayLabel")
        self.detailsTable = QtWidgets.QTableWidget(self.detailsFrame)
        self.detailsTable.setGeometry(QtCore.QRect(0, 216, 401, 391))
        self.detailsTable.setStyleSheet("background:white;\n"
"border:0px;")
        self.detailsTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.detailsTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.detailsTable.setShowGrid(True)
        self.detailsTable.setObjectName("detailsTable")
        self.detailsTable.setColumnCount(3)
        self.detailsTable.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.detailsTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailsTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailsTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailsTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailsTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailsTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailsTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.detailsTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailsTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailsTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(97, 212, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.detailsTable.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailsTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailsTable.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.detailsTable.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailsTable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailsTable.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(97, 212, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.detailsTable.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailsTable.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailsTable.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(97, 212, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.detailsTable.setItem(4, 2, item)
        self.detailsTable.horizontalHeader().setVisible(True)
        self.detailsTable.horizontalHeader().setCascadingSectionResizes(False)
        self.detailsTable.horizontalHeader().setHighlightSections(True)
        self.detailsTable.horizontalHeader().setSortIndicatorShown(False)
        self.detailsTable.horizontalHeader().setStretchLastSection(True)
        self.detailsTable.verticalHeader().setVisible(False)
        self.detailsTable.verticalHeader().setCascadingSectionResizes(False)
        self.detailsTable.verticalHeader().setHighlightSections(True)
        self.detailsTable.verticalHeader().setSortIndicatorShown(False)
        self.detailsTable.verticalHeader().setStretchLastSection(False)
        self.detailsSpotifyLabel = QtWidgets.QLabel(self.detailsFrame)
        self.detailsSpotifyLabel.setGeometry(QtCore.QRect(40, 720, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(9)
        self.detailsSpotifyLabel.setFont(font)
        self.detailsSpotifyLabel.setStyleSheet("color:white;\n"
"background: rgb(0,0,0,0);")
        self.detailsSpotifyLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.detailsSpotifyLabel.setObjectName("detailsSpotifyLabel")
        self.detailsAppleLabel = QtWidgets.QLabel(self.detailsFrame)
        self.detailsAppleLabel.setGeometry(QtCore.QRect(133, 710, 51, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(8)
        self.detailsAppleLabel.setFont(font)
        self.detailsAppleLabel.setStyleSheet("color:white;\n"
"background: rgb(0,0,0,0);")
        self.detailsAppleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.detailsAppleLabel.setObjectName("detailsAppleLabel")
        self.detailsYouLabel = QtWidgets.QLabel(self.detailsFrame)
        self.detailsYouLabel.setGeometry(QtCore.QRect(215, 720, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(9)
        self.detailsYouLabel.setFont(font)
        self.detailsYouLabel.setStyleSheet("color:white;\n"
"background: rgb(0,0,0,0);")
        self.detailsYouLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.detailsYouLabel.setObjectName("detailsYouLabel")
        self.detailsYandexLabel = QtWidgets.QLabel(self.detailsFrame)
        self.detailsYandexLabel.setGeometry(QtCore.QRect(300, 720, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(8)
        self.detailsYandexLabel.setFont(font)
        self.detailsYandexLabel.setStyleSheet("color:white;\n"
"background: rgb(0,0,0,0);")
        self.detailsYandexLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.detailsYandexLabel.setObjectName("detailsYandexLabel")
        self.detailsSlot2 = QtWidgets.QLabel(self.detailsFrame)
        self.detailsSlot2.setGeometry(QtCore.QRect(0, 170, 401, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(11)
        self.detailsSlot2.setFont(font)
        self.detailsSlot2.setStyleSheet("color:white;\n"
"background: #01A7FF;\n"
"border-radius:20px;\n"
"")
        self.detailsSlot2.setAlignment(QtCore.Qt.AlignCenter)
        self.detailsSlot2.setObjectName("detailsSlot2")
        self.detailsSlot3.raise_()
        self.detailsOpt.raise_()
        self.detailsSlot1.raise_()
        self.detailsYandex.raise_()
        self.detailsSongName.raise_()
        self.detailsArtist.raise_()
        self.detailsYou.raise_()
        self.detailsApple.raise_()
        self.detailsSpotify.raise_()
        self.detailsTopLabel.raise_()
        self.detailsBackBut.raise_()
        self.detailsPlayLabel.raise_()
        self.detailsSpotifyLabel.raise_()
        self.detailsAppleLabel.raise_()
        self.detailsYouLabel.raise_()
        self.detailsYandexLabel.raise_()
        self.detailsSlot2.raise_()
        self.detailsTable.raise_()


        self.retranslateUi(MAIN)
        QtCore.QMetaObject.connectSlotsByName(MAIN)

    def retranslateUi(self, MAIN):
        _translate = QtCore.QCoreApplication.translate
        MAIN.setWindowTitle(_translate("MAIN", "Apollo"))
        self.label_3.setText(_translate("MAIN", "A P O L L O"))
        self.username.setPlaceholderText(_translate("MAIN", "Username"))
        self.password.setPlaceholderText(_translate("MAIN", "Password"))
        self.loginBut.setText(_translate("MAIN", "Log In"))
        self.label_6.setText(_translate("MAIN", "Don\'t have an account?"))
        self.label_7.setText(_translate("MAIN", "Sign Up"))
        self.songNameList.setSortingEnabled(False)
        __sortingEnabled = self.songNameList.isSortingEnabled()
        self.songNameList.setSortingEnabled(False)
        item = self.songNameList.item(0)
        item.setText(_translate("MAIN", "Master of Puppets - Metallica"))
        item = self.songNameList.item(1)
        item.setText(_translate("MAIN", "Fear of the Dark - Iron Maiden"))
        item = self.songNameList.item(2)
        item.setText(_translate("MAIN", "Geceler - Ezhel"))
        item = self.songNameList.item(3)
        item.setText(_translate("MAIN", "Gülpembe - Barış Manço"))
        item = self.songNameList.item(4)
        item.setText(_translate("MAIN", "Statesboro Blues - Taj Mahal"))
        item = self.songNameList.item(5)
        item.setText(_translate("MAIN", "Billie Jean - Micheal Jackson"))
        item = self.songNameList.item(6)
        item.setText(_translate("MAIN", "Until The World Goes Cold - Trivium"))
        item = self.songNameList.item(7)
        item.setText(_translate("MAIN", "Ceviz Ağacı - Cem Karaca"))
        self.songNameList.setSortingEnabled(__sortingEnabled)
        self.songCountList.setSortingEnabled(False)
        __sortingEnabled = self.songCountList.isSortingEnabled()
        self.songCountList.setSortingEnabled(False)
        item = self.songCountList.item(0)
        item.setText(_translate("MAIN", "23"))
        item = self.songCountList.item(1)
        item.setText(_translate("MAIN", "20"))
        item = self.songCountList.item(2)
        item.setText(_translate("MAIN", "17"))
        item = self.songCountList.item(3)
        item.setText(_translate("MAIN", "15"))
        item = self.songCountList.item(4)
        item.setText(_translate("MAIN", "14"))
        item = self.songCountList.item(5)
        item.setText(_translate("MAIN", "11"))
        item = self.songCountList.item(6)
        item.setText(_translate("MAIN", "5"))
        item = self.songCountList.item(7)
        item.setText(_translate("MAIN", "2"))
        self.songCountList.setSortingEnabled(__sortingEnabled)
        self.locLabel.setText(_translate("MAIN", "Kadıköy, Istanbul, TURKEY"))
        self.songWeekLabel.setText(_translate("MAIN", "Song of the week:"))
        self.weekSongLabel.setText(_translate("MAIN", "Master of Puppets - Metallica"))
        self.historyTopLabel.setText(_translate("MAIN", "History"))
        self.historyLineEdit.setPlaceholderText(_translate("MAIN", "Search in your history"))
        __sortingEnabled = self.historySongList.isSortingEnabled()
        self.historySongList.setSortingEnabled(False)
        item = self.historySongList.item(0)
        item.setText(_translate("MAIN", "Until The World Goes Cold - Trivium"))
        item = self.historySongList.item(1)
        item.setText(_translate("MAIN", "Dark Horse - Katy Perry"))
        item = self.historySongList.item(2)
        item.setText(_translate("MAIN", "Smooth Criminal - Micheal Jackson"))
        self.historySongList.setSortingEnabled(__sortingEnabled)
        self.friend1Name.setText(_translate("MAIN", "@rick.n.morty"))
        self.friend1Info.setText(_translate("MAIN", "Shared 12 songs this week"))
        self.friend2Info.setText(_translate("MAIN", "Shared 20 songs this week"))
        self.friend2Name.setText(_translate("MAIN", "@havni.gul17"))
        self.friend3Info.setText(_translate("MAIN", "Shared 7 songs this week"))
        self.friend3Name.setText(_translate("MAIN", "@cagatay.savasli"))
        self.friend4Name.setText(_translate("MAIN", "@mariaa2moon"))
        self.friend4Info.setText(_translate("MAIN", "Shared 16 songs this week"))
        self.friendsTopLabel.setText(_translate("MAIN", "Friends"))
        self.worldTopLabel.setText(_translate("MAIN", "Discover"))
        self.routeTopLabel.setText(_translate("MAIN", "Route"))
        self.comboBox.setCurrentText(_translate("MAIN", "Select a category"))
        self.comboBox.setItemText(0, _translate("MAIN", "Select a category"))
        self.comboBox.setItemText(1, _translate("MAIN", "Metal"))
        self.comboBox.setItemText(2, _translate("MAIN", "Rock"))
        self.comboBox.setItemText(3, _translate("MAIN", "Rap"))
        self.comboBox.setItemText(4, _translate("MAIN", "Pop"))
        self.comboBox.setItemText(5, _translate("MAIN", "Blues"))
        self.shareTopLabel.setText(_translate("MAIN", "Share"))
        self.shareSearchBox.setPlaceholderText(_translate("MAIN", "Search for a music"))
        self.shareShareBut.setText(_translate("MAIN", "Share!"))
        self.successLabel.setText(_translate("MAIN", "Music shared!"))
        self.detailsSongName.setText(_translate("MAIN", "Until The World Goes Cold"))
        self.detailsArtist.setText(_translate("MAIN", "Trivium"))
        self.detailsTopLabel.setText(_translate("MAIN", "Details"))
        self.detailsPlayLabel.setText(_translate("MAIN", "Play with"))
        item = self.detailsTable.horizontalHeaderItem(0)
        item.setText(_translate("MAIN", "User"))
        item = self.detailsTable.horizontalHeaderItem(1)
        item.setText(_translate("MAIN", "Date"))
        item = self.detailsTable.horizontalHeaderItem(2)
        item.setText(_translate("MAIN", "Follow"))
        __sortingEnabled = self.detailsTable.isSortingEnabled()
        self.detailsTable.setSortingEnabled(False)
        item = self.detailsTable.item(0, 0)
        item.setText(_translate("MAIN", "@rick.n.morty"))
        item = self.detailsTable.item(0, 1)
        item.setText(_translate("MAIN", "1 hour ago"))
        item = self.detailsTable.item(0, 2)
        item.setText(_translate("MAIN", "Unfollow"))
        item = self.detailsTable.item(1, 0)
        item.setText(_translate("MAIN", "@xrays7777"))
        item = self.detailsTable.item(1, 1)
        item.setText(_translate("MAIN", "1 hour ago"))
        item = self.detailsTable.item(1, 2)
        item.setText(_translate("MAIN", "Follow"))
        item = self.detailsTable.item(2, 0)
        item.setText(_translate("MAIN", "@cagatay.savasli"))
        item = self.detailsTable.item(2, 1)
        item.setText(_translate("MAIN", "3 hours ago"))
        item = self.detailsTable.item(2, 2)
        item.setText(_translate("MAIN", "Unfollow"))
        item = self.detailsTable.item(3, 0)
        item.setText(_translate("MAIN", "@sangirtioda14"))
        item = self.detailsTable.item(3, 1)
        item.setText(_translate("MAIN", "Yesterday"))
        item = self.detailsTable.item(3, 2)
        item.setText(_translate("MAIN", "Follow"))
        item = self.detailsTable.item(4, 0)
        item.setText(_translate("MAIN", "@katie1"))
        item = self.detailsTable.item(4, 1)
        item.setText(_translate("MAIN", "17.07.2020"))
        item = self.detailsTable.item(4, 2)
        item.setText(_translate("MAIN", "Follow"))
        self.detailsTable.setSortingEnabled(__sortingEnabled)
        self.detailsSpotifyLabel.setText(_translate("MAIN", "Spotify"))
        self.detailsAppleLabel.setText(_translate("MAIN", "Apple\n"
"Music"))
        self.detailsYouLabel.setText(_translate("MAIN", "YouTube"))
        self.detailsYandexLabel.setText(_translate("MAIN", "Yandex\n"
"Music"))
        self.detailsSlot2.setText(_translate("MAIN", "This week"))