# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'homeNEW.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MAIN(object):
    def setupUi(self, MAIN):
        MAIN.setObjectName("MAIN")
        MAIN.resize(468, 887)
        MAIN.setMinimumSize(QtCore.QSize(468, 887))
        MAIN.setMaximumSize(QtCore.QSize(468, 887))
        self.label = QtWidgets.QLabel(MAIN)
        self.label.setGeometry(QtCore.QRect(0, 0, 463, 901))
        self.label.setMinimumSize(QtCore.QSize(463, 901))
        self.label.setMaximumSize(QtCore.QSize(463, 901))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/phone.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.homeFrame = QtWidgets.QFrame(MAIN)
        self.homeFrame.setGeometry(QtCore.QRect(31, 58, 401, 772))
        self.homeFrame.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0.0738636 #205AFF, stop:0.840909 #1180FF);")
        self.homeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.homeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.homeFrame.setObjectName("homeFrame")
        self.settingsBut = QtWidgets.QPushButton(self.homeFrame)
        self.settingsBut.setGeometry(QtCore.QRect(20, 20, 40, 40))
        self.settingsBut.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.settingsBut.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsBut.setIcon(icon)
        self.settingsBut.setIconSize(QtCore.QSize(30, 30))
        self.settingsBut.setObjectName("settingsBut")
        self.profileBut = QtWidgets.QPushButton(self.homeFrame)
        self.profileBut.setGeometry(QtCore.QRect(340, 20, 40, 40))
        self.profileBut.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.profileBut.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.profileBut.setIcon(icon1)
        self.profileBut.setIconSize(QtCore.QSize(30, 30))
        self.profileBut.setObjectName("profileBut")
        self.musicBut = QtWidgets.QPushButton(self.homeFrame)
        self.musicBut.setGeometry(QtCore.QRect(150, 670, 100, 100))
        self.musicBut.setStyleSheet("background-color: #66CCFF;\n"
"border:0px;\n"
"border-radius:50px;")
        self.musicBut.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/sign.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.musicBut.setIcon(icon2)
        self.musicBut.setIconSize(QtCore.QSize(60, 60))
        self.musicBut.setObjectName("musicBut")
        self.botBackLabel = QtWidgets.QLabel(self.homeFrame)
        self.botBackLabel.setGeometry(QtCore.QRect(19, 700, 371, 51))
        self.botBackLabel.setStyleSheet("background-color: #01A7FF;\n"
"border:0px;\n"
"border-radius:20px;")
        self.botBackLabel.setText("")
        self.botBackLabel.setObjectName("botBackLabel")
        self.worldBut = QtWidgets.QPushButton(self.homeFrame)
        self.worldBut.setGeometry(QtCore.QRect(340, 705, 40, 40))
        self.worldBut.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.worldBut.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/world.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.worldBut.setIcon(icon3)
        self.worldBut.setIconSize(QtCore.QSize(35, 35))
        self.worldBut.setObjectName("worldBut")
        self.likeBut = QtWidgets.QPushButton(self.homeFrame)
        self.likeBut.setGeometry(QtCore.QRect(30, 705, 40, 40))
        self.likeBut.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.likeBut.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("img/liked.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.likeBut.setIcon(icon4)
        self.likeBut.setIconSize(QtCore.QSize(35, 35))
        self.likeBut.setObjectName("likeBut")
        self.mapLabel = QtWidgets.QLabel(self.homeFrame)
        self.mapLabel.setGeometry(QtCore.QRect(0, 120, 401, 200))
        self.mapLabel.setText("")
        self.mapLabel.setPixmap(QtGui.QPixmap("img/gps.png"))
        self.mapLabel.setScaledContents(True)
        self.mapLabel.setObjectName("mapLabel")
        self.friendsBut = QtWidgets.QPushButton(self.homeFrame)
        self.friendsBut.setGeometry(QtCore.QRect(90, 705, 40, 40))
        self.friendsBut.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.friendsBut.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("img/friend.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.friendsBut.setIcon(icon5)
        self.friendsBut.setIconSize(QtCore.QSize(35, 35))
        self.friendsBut.setObjectName("friendsBut")
        self.routeBut = QtWidgets.QPushButton(self.homeFrame)
        self.routeBut.setGeometry(QtCore.QRect(270, 705, 40, 40))
        self.routeBut.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.routeBut.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("img/Route.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.routeBut.setIcon(icon6)
        self.routeBut.setIconSize(QtCore.QSize(35, 35))
        self.routeBut.setObjectName("routeBut")
        self.songNameList = QtWidgets.QListWidget(self.homeFrame)
        self.songNameList.setGeometry(QtCore.QRect(0, 340, 321, 241))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(11)
        self.songNameList.setFont(font)
        self.songNameList.setStyleSheet("background:white;\n"
"color:gray;\n"
"border:0px;")
        self.songNameList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.songNameList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.songNameList.setIconSize(QtCore.QSize(15, 15))
        self.songNameList.setMovement(QtWidgets.QListView.Static)
        self.songNameList.setFlow(QtWidgets.QListView.TopToBottom)
        self.songNameList.setProperty("isWrapping", False)
        self.songNameList.setViewMode(QtWidgets.QListView.ListMode)
        self.songNameList.setUniformItemSizes(False)
        self.songNameList.setWordWrap(False)
        self.songNameList.setSelectionRectVisible(False)
        self.songNameList.setObjectName("songNameList")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.songNameList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.songNameList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.songNameList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.songNameList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.songNameList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.songNameList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.songNameList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.songNameList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.songNameList.addItem(item)
        self.songCountList = QtWidgets.QListWidget(self.homeFrame)
        self.songCountList.setGeometry(QtCore.QRect(321, 340, 51, 241))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(11)
        self.songCountList.setFont(font)
        self.songCountList.setStyleSheet("background:white;\n"
"color:green;\n"
"border:0px;")
        self.songCountList.setIconSize(QtCore.QSize(15, 15))
        self.songCountList.setMovement(QtWidgets.QListView.Static)
        self.songCountList.setFlow(QtWidgets.QListView.TopToBottom)
        self.songCountList.setProperty("isWrapping", False)
        self.songCountList.setViewMode(QtWidgets.QListView.ListMode)
        self.songCountList.setUniformItemSizes(False)
        self.songCountList.setWordWrap(False)
        self.songCountList.setSelectionRectVisible(False)
        self.songCountList.setObjectName("songCountList")
        item = QtWidgets.QListWidgetItem()
        self.songCountList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.songCountList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.songCountList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.songCountList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.songCountList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.songCountList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.songCountList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.songCountList.addItem(item)
        self.locLabel = QtWidgets.QLabel(self.homeFrame)
        self.locLabel.setGeometry(QtCore.QRect(0, 80, 401, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setBold(True)
        font.setWeight(75)
        self.locLabel.setFont(font)
        self.locLabel.setStyleSheet("color:white;\n"
"background:#1180FF;")
        self.locLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.locLabel.setObjectName("locLabel")
        self.weekBackLabel = QtWidgets.QLabel(self.homeFrame)
        self.weekBackLabel.setGeometry(QtCore.QRect(20, 600, 371, 61))
        self.weekBackLabel.setStyleSheet("background: #01A7FF;\n"
"border-radius:15px;")
        self.weekBackLabel.setText("")
        self.weekBackLabel.setObjectName("weekBackLabel")
        self.songWeekLabel = QtWidgets.QLabel(self.homeFrame)
        self.songWeekLabel.setGeometry(QtCore.QRect(20, 600, 371, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.songWeekLabel.setFont(font)
        self.songWeekLabel.setStyleSheet("background: rgb(0,0,0,0);\n"
"color:yellow;")
        self.songWeekLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.songWeekLabel.setObjectName("songWeekLabel")
        self.weekSongLabel = QtWidgets.QLabel(self.homeFrame)
        self.weekSongLabel.setGeometry(QtCore.QRect(20, 630, 371, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.weekSongLabel.setFont(font)
        self.weekSongLabel.setStyleSheet("background: rgb(0,0,0,0);\n"
"color:#d3d4e0;")
        self.weekSongLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.weekSongLabel.setObjectName("weekSongLabel")
        self.settingsBut.raise_()
        self.profileBut.raise_()
        self.botBackLabel.raise_()
        self.worldBut.raise_()
        self.mapLabel.raise_()
        self.routeBut.raise_()
        self.songNameList.raise_()
        self.likeBut.raise_()
        self.friendsBut.raise_()
        self.songCountList.raise_()
        self.locLabel.raise_()
        self.weekBackLabel.raise_()
        self.musicBut.raise_()
        self.songWeekLabel.raise_()
        self.weekSongLabel.raise_()

        self.retranslateUi(MAIN)
        QtCore.QMetaObject.connectSlotsByName(MAIN)

    def retranslateUi(self, MAIN):
        _translate = QtCore.QCoreApplication.translate
        MAIN.setWindowTitle(_translate("MAIN", "Apollo"))
        self.songNameList.setSortingEnabled(False)
        __sortingEnabled = self.songNameList.isSortingEnabled()
        self.songNameList.setSortingEnabled(False)
        item = self.songNameList.item(0)
        item.setText(_translate("MAIN", "Master of Puppets - Metallica"))
        item = self.songNameList.item(1)
        item.setText(_translate("MAIN", "Fear of the Dark - Iron Maiden"))
        item = self.songNameList.item(2)
        item.setText(_translate("MAIN", "Geceler - Ezhel"))
        item = self.songNameList.item(3)
        item.setText(_translate("MAIN", "Gülpembe - Barış Manço"))
        item = self.songNameList.item(4)
        item.setText(_translate("MAIN", "Statesboro Blues - Taj Mahal"))
        item = self.songNameList.item(5)
        item.setText(_translate("MAIN", "Billie Jean - Micheal Jackson"))
        item = self.songNameList.item(6)
        item.setText(_translate("MAIN", "Until The World Goes Cold - Trivium"))
        item = self.songNameList.item(7)
        item.setText(_translate("MAIN", "Ceviz Ağacı - Cem Karaca"))
        item = self.songNameList.item(8)
        item.setText(_translate("MAIN", "Smoke on the Water - Deep Purple"))
        self.songNameList.setSortingEnabled(__sortingEnabled)
        self.songCountList.setSortingEnabled(False)
        __sortingEnabled = self.songCountList.isSortingEnabled()
        self.songCountList.setSortingEnabled(False)
        item = self.songCountList.item(0)
        item.setText(_translate("MAIN", "162"))
        item = self.songCountList.item(1)
        item.setText(_translate("MAIN", "128"))
        item = self.songCountList.item(2)
        item.setText(_translate("MAIN", "93"))
        item = self.songCountList.item(3)
        item.setText(_translate("MAIN", "72"))
        item = self.songCountList.item(4)
        item.setText(_translate("MAIN", "54"))
        item = self.songCountList.item(5)
        item.setText(_translate("MAIN", "39"))
        item = self.songCountList.item(6)
        item.setText(_translate("MAIN", "24"))
        item = self.songCountList.item(7)
        item.setText(_translate("MAIN", "11"))
        self.songCountList.setSortingEnabled(__sortingEnabled)
        self.locLabel.setText(_translate("MAIN", "Kadıköy, Istanbul, TURKEY"))
        self.songWeekLabel.setText(_translate("MAIN", "Song of the week:"))
        self.weekSongLabel.setText(_translate("MAIN", "Geceler - Ezhel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MAIN = QtWidgets.QWidget()
    ui = Ui_MAIN()
    ui.setupUi(MAIN)
    MAIN.show()
    sys.exit(app.exec_())

