# -*- coding: utf-8 -*-

# Created by Atahan Caldir

from PyQt5 import QtCore, QtGui, QtWidgets

####################################################### BOOK LIST ITEM #######################################################

class Ui_bookItemWindow(QtWidgets.QWidget):

    """
    editButClickedSignal = QtCore.pyqtSignal(list)
    pinButClickedSignal = QtCore.pyqtSignal(list)"""

    def __init__ (self, parent = None):
        super(Ui_bookItemWindow, self).__init__(parent)

        self.textQHBoxLayoutLeft = QtWidgets.QHBoxLayout()
        self.imgLabel = QtWidgets.QLabel()
        self.imgLabel.setMinimumSize(QtCore.QSize(150, 150))
        self.imgLabel.setMaximumSize(QtCore.QSize(150, 150))
        self.imgLabel.setStyleSheet("background: #DFE2EA;")
        self.indicatorLabel = QtWidgets.QLabel()
        self.indicatorLabel.setMinimumSize(QtCore.QSize(10, 150))
        self.indicatorLabel.setMaximumSize(QtCore.QSize(10, 150))
        self.indicatorLabel.setStyleSheet("background: #DFE2EA;")
        self.textQHBoxLayoutLeft.addWidget(self.imgLabel)
        self.textQHBoxLayoutLeft.addWidget(self.indicatorLabel)

        self.textQVBoxLayout = QtWidgets.QVBoxLayout()
        self.bookNameLabel = QtWidgets.QLabel()
        self.bookNameLabel.setMinimumSize(QtCore.QSize(600, 50))
        self.bookNameLabel.setMaximumSize(QtCore.QSize(600, 50))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(13)
        font.setWeight(75)
        self.bookNameLabel.setFont(font)
        self.bookNameLabel.setStyleSheet("background: #DFE2EA;")
        self.bookNameLabel.setWordWrap(True)
        self.authorLabel = QtWidgets.QLabel()
        self.authorLabel.setMinimumSize(QtCore.QSize(600, 45))
        self.authorLabel.setMaximumSize(QtCore.QSize(600, 45))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.authorLabel.setFont(font)
        self.authorLabel.setStyleSheet("background: #DFE2EA;")
        self.authorLabel.setWordWrap(True)
        self.pageLabel = QtWidgets.QLabel()
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.pageLabel.setFont(font)
        self.pageLabel.setStyleSheet("background: #DFE2EA;")
        self.pageLabel.setMaximumSize(QtCore.QSize(600, 30))
        self.categoryLabel = QtWidgets.QLabel()
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.categoryLabel.setFont(font)
        self.categoryLabel.setStyleSheet("background: #DFE2EA; color: #3B3A36;")
        self.categoryLabel.setMaximumSize(QtCore.QSize(600, 42))
        self.textQVBoxLayout.addWidget(self.bookNameLabel)
        self.textQVBoxLayout.addWidget(self.authorLabel)
        self.textQVBoxLayout.addWidget(self.pageLabel)
        self.textQVBoxLayout.addWidget(self.categoryLabel)

        self.buttonsQVBoxLayout = QtWidgets.QVBoxLayout()
        self.pinBut = QtWidgets.QPushButton()
        self.pinBut.setMinimumSize(QtCore.QSize(50, 50))
        self.pinBut.setMaximumSize(QtCore.QSize(50, 50))
        self.pinBut.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("media/pin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pinBut.setIcon(icon)
        self.pinBut.setIconSize(QtCore.QSize(30, 30))
        self.editBut = QtWidgets.QPushButton()
        self.editBut.setMinimumSize(QtCore.QSize(50, 50))
        self.editBut.setMaximumSize(QtCore.QSize(50, 50))
        self.editBut.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.editBut.setStyleSheet("border: 0px; border-radius: 20px; background: #DFE2EA;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("media/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editBut.setIcon(icon1)
        self.editBut.setIconSize(QtCore.QSize(25, 25))
        self.buttonsQVBoxLayout.addWidget(self.pinBut)
        self.buttonsQVBoxLayout.addWidget(self.editBut)

        self.allQHBoxLayout = QtWidgets.QHBoxLayout()
        self.allQHBoxLayout.addLayout(self.textQHBoxLayoutLeft, 0)
        self.allQHBoxLayout.addLayout(self.textQVBoxLayout, 1)
        self.allQHBoxLayout.addLayout(self.buttonsQVBoxLayout, 2)
        self.setLayout(self.allQHBoxLayout)

        """
        self.pinBut.clicked.connect(lambda: self.butClicked(0))
        self.editBut.clicked.connect(lambda: self.butClicked(1))
        """
    def setBookDetails(self, bookName, author, page, category, path, pinned = "no"):
        self.bookNameLabel.setText(bookName)
        self.authorLabel.setText(author)
        self.pageLabel.setText(page)
        self.categoryLabel.setText(category)

        pixmap = QtGui.QPixmap(path)
        pixmap = pixmap.scaledToWidth(150)
        pixmap = pixmap.scaledToHeight(150)
        self.imgLabel.setPixmap(pixmap)

        if pinned == "yes":
            self.pinBut.setStyleSheet("border: 0px;\n"
"border-radius: 20px;\n"
"background: #2AC267;")
        else:
            self.pinBut.setStyleSheet("border: 0px;\n"
"border-radius: 20px;\n"
"background: #DFE2EA;")

    #below will be edited
    """
    def butClicked(self, index):
        bookName = self.bookNameLabel.text()
        authorName = self.authorLabel.text()
        pageCount = self.pageLabel.text()
        categoryName = self.categoryLabel.text()

        if index == 0:
            self.pinButClickedSignal.emit([bookName, authorName, pageCount, categoryName])
        else:
            self.editButClickedSignal.emit([bookName, authorName, pageCount, categoryName])
    """
####################################################### MAIN WINDOW #######################################################

class Ui_MAIN(QtWidgets.QWidget):
    def __init__(self):
        QtWidgets.QWidget.__init__(self)
        self.setupUi(self)

    def setupUi(self, MAIN):
        MAIN.setObjectName("MAIN")
        MAIN.resize(1176, 800)
        MAIN.setMinimumSize(QtCore.QSize(1176, 800))
        MAIN.setMaximumSize(QtCore.QSize(1176, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("media/Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MAIN.setWindowIcon(icon)
        MAIN.setStyleSheet("background:white;")
        self.frame = QtWidgets.QFrame(MAIN)
        self.frame.setGeometry(QtCore.QRect(0, 0, 895, 61))
        self.frame.setStyleSheet("background: #3F528A;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(10, 10, 511, 41))
        self.widget.setStyleSheet("background: white;\n"
"border-radius: 5px;")
        self.widget.setObjectName("widget")
        self.searchLine = QtWidgets.QLineEdit(self.widget)
        self.searchLine.setGeometry(QtCore.QRect(9, 7, 431, 29))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.searchLine.setFont(font)
        self.searchLine.setStyleSheet("border: 0px;")
        self.searchLine.setObjectName("searchLine")
        self.searchBut = QtWidgets.QPushButton(self.widget)
        self.searchBut.setGeometry(QtCore.QRect(440, 7, 71, 29))
        self.searchBut.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.searchBut.setStyleSheet("border: 0px;")
        self.searchBut.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("media/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchBut.setIcon(icon1)
        self.searchBut.setObjectName("searchBut")
        self.categoryCombo = QtWidgets.QComboBox(self.frame)
        self.categoryCombo.setGeometry(QtCore.QRect(525, 10, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.categoryCombo.setFont(font)
        self.categoryCombo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.categoryCombo.setStyleSheet("background: white;")
        self.categoryCombo.setObjectName("categoryCombo")
        self.categoryCombo.addItem("")
        self.categoryCombo.addItem("")
        self.categoryCombo.addItem("")
        self.categoryCombo.addItem("")
        self.categoryCombo.addItem("")
        self.categoryCombo.addItem("")
        self.categoryCombo.addItem("")
        self.categoryCombo.addItem("")
        self.categoryCombo.addItem("")
        self.categoryCombo.addItem("")
        self.categoryCombo.addItem("")
        self.categoryCombo.addItem("")
        self.categoryCombo.addItem("")
        self.categoryCombo.addItem("")
        self.categoryCombo.addItem("")
        self.categoryCombo.addItem("")
        self.categoryCombo.addItem("")
        self.categoryCombo.addItem("")
        self.categoryCombo.setItemData(0, QtGui.QColor("orange"), QtCore.Qt.BackgroundColorRole)
        for i in range(1,17):
            self.categoryCombo.setItemData(i, QtGui.QColor("white"), QtCore.Qt.ForegroundRole)
        self.categoryCombo.setItemData(17, QtGui.QColor("orange"), QtCore.Qt.BackgroundColorRole)
        self.sortCombo = QtWidgets.QComboBox(self.frame)
        self.sortCombo.setGeometry(QtCore.QRect(713, 10, 175, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sortCombo.setFont(font)
        self.sortCombo.setStyleSheet("background: white;")
        self.sortCombo.setObjectName("sortCombo")
        self.sortCombo.addItem("")
        self.sortCombo.addItem("")
        self.sortCombo.addItem("")
        self.sortCombo.addItem("")
        self.sortCombo.addItem("")
        self.sortCombo.addItem("")
        self.sortCombo.addItem("")
        for i in range(7):
            self.sortCombo.setItemData(i, QtGui.QColor("white"), QtCore.Qt.ForegroundRole)
        self.sortCombo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bookList = QtWidgets.QListWidget(MAIN)
        self.bookList.setGeometry(QtCore.QRect(-1, 61, 896, 740))
        self.bookList.setStyleSheet("QListWidget { background: #DFE2EA; } QListWidget::item { border-bottom: 3px solid black; }")
        self.bookList.setObjectName("bookList")
        self.frame_2 = QtWidgets.QFrame(MAIN)
        self.frame_2.setGeometry(QtCore.QRect(895, 0, 281, 800))
        self.frame_2.setStyleSheet("background: #222F57;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.addBookBut = QtWidgets.QPushButton(self.frame_2)
        self.addBookBut.setGeometry(QtCore.QRect(30, 40, 40, 40))
        self.addBookBut.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addBookBut.setStyleSheet("background: #2AC267;\n"
"border-radius: 5px;")
        self.addBookBut.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("media/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addBookBut.setIcon(icon2)
        self.addBookBut.setIconSize(QtCore.QSize(30, 30))
        self.addBookBut.setObjectName("addBookBut")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(20, 80, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #29B461;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(110, 80, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #29B461;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.shuffleBut = QtWidgets.QPushButton(self.frame_2)
        self.shuffleBut.setGeometry(QtCore.QRect(120, 40, 40, 40))
        self.shuffleBut.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.shuffleBut.setStyleSheet("background: #2AC267;\n"
"border-radius: 5px;")
        self.shuffleBut.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("media/random.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shuffleBut.setIcon(icon3)
        self.shuffleBut.setIconSize(QtCore.QSize(30, 30))
        self.shuffleBut.setObjectName("shuffleBut")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(200, 80, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #29B461;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.notesBut = QtWidgets.QPushButton(self.frame_2)
        self.notesBut.setGeometry(QtCore.QRect(210, 40, 40, 40))
        self.notesBut.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.notesBut.setStyleSheet("background: #2AC267;\n"
"border-radius: 5px;")
        self.notesBut.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("media/notes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.notesBut.setIcon(icon4)
        self.notesBut.setIconSize(QtCore.QSize(30, 30))
        self.notesBut.setObjectName("notesBut")
        self.readProgress = QtWidgets.QProgressBar(self.frame_2)
        self.readProgress.setGeometry(QtCore.QRect(20, 240, 241, 23))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.readProgress.setFont(font)
        self.readProgress.setStyleSheet("QProgressBar\n"
"{\n"
"    color: #313235;\n"
"    border-radius: 5px;\n"
"    background-color:white;\n"
"}\n"
"QProgressBar::chunk\n"
"{\n"
"    border-radius: 5px;\n"
"    background-color: #7895EB;\n"
"}")
        self.readProgress.setAlignment(QtCore.Qt.AlignCenter)
        self.readProgress.setObjectName("readProgress")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(40, 740, 50, 50))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("media/Logo.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.line = QtWidgets.QFrame(self.frame_2)
        self.line.setGeometry(QtCore.QRect(10, 120, 261, 1))
        self.line.setStyleSheet("border: 2px solid gray;")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.bookCount = QtWidgets.QLCDNumber(self.frame_2)
        self.bookCount.setGeometry(QtCore.QRect(17, 140, 71, 41))
        self.bookCount.setStyleSheet("color: white;")
        self.bookCount.setObjectName("bookCount")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(25, 180, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: #7D86A1;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.readCount = QtWidgets.QLCDNumber(self.frame_2)
        self.readCount.setGeometry(QtCore.QRect(105, 140, 71, 41))
        self.readCount.setStyleSheet("color: white;")
        self.readCount.setObjectName("readCount")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(113, 180, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: #7D86A1;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.ownCount = QtWidgets.QLCDNumber(self.frame_2)
        self.ownCount.setGeometry(QtCore.QRect(193, 140, 71, 41))
        self.ownCount.setStyleSheet("color: white;")
        self.ownCount.setObjectName("ownCount")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(201, 180, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: #7D86A1;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.line_2 = QtWidgets.QFrame(self.frame_2)
        self.line_2.setGeometry(QtCore.QRect(10, 290, 261, 1))
        self.line_2.setStyleSheet("border: 2px solid gray;")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(90, 755, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: white;")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(10, 310, 261, 20))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: white;")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.pinnedList = QtWidgets.QListWidget(self.frame_2)
        self.pinnedList.setGeometry(QtCore.QRect(10, 340, 261, 391))
        self.pinnedList.setStyleSheet("background: #7895EB;")
        self.pinnedList.setObjectName("pinnedList")

        self.retranslateUi(MAIN)
        QtCore.QMetaObject.connectSlotsByName(MAIN)

    def retranslateUi(self, MAIN):
        _translate = QtCore.QCoreApplication.translate
        MAIN.setWindowTitle(_translate("MAIN", "Platon"))
        self.searchLine.setPlaceholderText(_translate("MAIN", "Search for books"))
        self.categoryCombo.setItemText(0, _translate("bookDetailsWindow", "All Books"))
        self.categoryCombo.setItemText(1, _translate("bookDetailsWindow", "Academic"))
        self.categoryCombo.setItemText(2, _translate("bookDetailsWindow", "Art"))
        self.categoryCombo.setItemText(3, _translate("bookDetailsWindow", "Biography"))
        self.categoryCombo.setItemText(4, _translate("bookDetailsWindow", "Business"))
        self.categoryCombo.setItemText(5, _translate("bookDetailsWindow", "Comics"))
        self.categoryCombo.setItemText(6, _translate("bookDetailsWindow", "Economics"))
        self.categoryCombo.setItemText(7, _translate("bookDetailsWindow", "Essay"))
        self.categoryCombo.setItemText(8, _translate("bookDetailsWindow", "History"))
        self.categoryCombo.setItemText(9, _translate("bookDetailsWindow", "Law"))
        self.categoryCombo.setItemText(10, _translate("bookDetailsWindow", "Novel"))
        self.categoryCombo.setItemText(11, _translate("bookDetailsWindow", "Personal Evolution"))
        self.categoryCombo.setItemText(12, _translate("bookDetailsWindow", "Philosophy"))
        self.categoryCombo.setItemText(13, _translate("bookDetailsWindow", "Poetry"))
        self.categoryCombo.setItemText(14, _translate("bookDetailsWindow", "Politics"))
        self.categoryCombo.setItemText(15, _translate("bookDetailsWindow", "Religion"))
        self.categoryCombo.setItemText(16, _translate("bookDetailsWindow", "Science"))
        self.categoryCombo.setItemText(17, _translate("bookDetailsWindow", "Turkish Literature"))
        self.categoryCombo.setItemText(18, _translate("bookDetailsWindow", "World Literature"))
        self.categoryCombo.setItemText(19, _translate("bookDetailsWindow", "Research"))
        self.sortCombo.setItemText(0, _translate("mainWindow", "A>Z (Book Name)"))
        self.sortCombo.setItemText(1, _translate("mainWindow", "Z>A (Book Name)"))
        self.sortCombo.setItemText(2, _translate("mainWindow", "A>Z (Author Name)"))
        self.sortCombo.setItemText(3, _translate("mainWindow", "Z>A (Author Name)"))
        self.sortCombo.setItemText(4, _translate("mainWindow", "Page Count (Ascending)"))
        self.sortCombo.setItemText(5, _translate("mainWindow", "Owned Books"))
        self.sortCombo.setItemText(6, _translate("mainWindow", "Read Books"))
        self.label.setText(_translate("MAIN", "Add Book"))
        self.label_2.setText(_translate("MAIN", "Shuffle"))
        self.label_3.setText(_translate("MAIN", "Notes"))
        self.label_6.setText(_translate("MAIN", "Book\n"
"Count"))
        self.label_7.setText(_translate("MAIN", "Read\n"
"Count"))
        self.label_8.setText(_translate("MAIN", "Own\n"
"Count"))
        self.label_9.setText(_translate("MAIN", "Created by Atahan Çaldır"))
        self.label_10.setText(_translate("MAIN", "Pinned Books"))

####################################################### BOOK DETAILS #######################################################

class Ui_bookDetailsWindow(QtWidgets.QWidget):
    def __init__(self):
        QtWidgets.QWidget.__init__(self)
        self.setupUi(self)

    def setupUi(self, bookDetailsWindow):
        bookDetailsWindow.setObjectName("bookDetailsWindow")
        bookDetailsWindow.resize(997, 651)
        bookDetailsWindow.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("media/Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        bookDetailsWindow.setWindowIcon(icon)
        bookDetailsWindow.setStyleSheet("background:#222F57;")
        self.label = QtWidgets.QLabel(bookDetailsWindow)
        self.label.setGeometry(QtCore.QRect(120, 20, 861, 30))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(bookDetailsWindow)
        self.label_2.setGeometry(QtCore.QRect(120, 120, 861, 30))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white;")
        self.label_2.setObjectName("label_2")
        self.editBut = QtWidgets.QPushButton(bookDetailsWindow)
        self.editBut.setGeometry(QtCore.QRect(10, 10, 60, 60))
        self.editBut.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.editBut.setStyleSheet("background:#2AC267;\n"
"border-radius:10px;")
        self.editBut.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("media/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editBut.setIcon(icon)
        self.editBut.setIconSize(QtCore.QSize(45, 45))
        self.editBut.setObjectName("editBut")
        self.bookNameLabel = QtWidgets.QLineEdit(bookDetailsWindow)
        self.bookNameLabel.setEnabled(True)
        self.bookNameLabel.setGeometry(QtCore.QRect(120, 60, 861, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(10)
        font.setItalic(False)
        self.bookNameLabel.setFont(font)
        self.bookNameLabel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.bookNameLabel.setStyleSheet("background:#222F57;\n"
"border:0px;")
        self.bookNameLabel.setText("")
        self.bookNameLabel.setReadOnly(True)
        self.bookNameLabel.setClearButtonEnabled(False)
        self.bookNameLabel.setObjectName("bookNameLabel")
        self.authorLabel = QtWidgets.QLineEdit(bookDetailsWindow)
        self.authorLabel.setGeometry(QtCore.QRect(120, 160, 861, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(10)
        font.setItalic(False)
        self.authorLabel.setFont(font)
        self.authorLabel.setStyleSheet("background:#222F57;\n"
"border:0px;")
        self.authorLabel.setText("")
        self.authorLabel.setReadOnly(True)
        self.authorLabel.setObjectName("authorLabel")
        self.horizontalLayoutWidget = QtWidgets.QWidget(bookDetailsWindow)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(120, 210, 861, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: white;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: white;")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.pageLabel = QtWidgets.QLineEdit(bookDetailsWindow)
        self.pageLabel.setGeometry(QtCore.QRect(560, 270, 421, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(10)
        font.setItalic(False)
        self.pageLabel.setFont(font)
        self.pageLabel.setStyleSheet("background:#222F57;\n"
"border:0px;")
        self.pageLabel.setText("")
        self.pageLabel.setReadOnly(True)
        self.pageLabel.setObjectName("pageLabel")
        self.ownCheck = QtWidgets.QCheckBox(bookDetailsWindow)
        self.ownCheck.setGeometry(QtCore.QRect(120, 320, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        self.ownCheck.setFont(font)
        self.ownCheck.setObjectName("ownCheck")
        self.ownCheck.setStyleSheet("color: white;")
        self.readCheck = QtWidgets.QCheckBox(bookDetailsWindow)
        self.readCheck.setGeometry(QtCore.QRect(230, 320, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        self.readCheck.setFont(font)
        self.readCheck.setObjectName("readCheck")
        self.readCheck.setStyleSheet("color: white;")
        self.saveBut = QtWidgets.QPushButton(bookDetailsWindow)
        self.saveBut.setGeometry(QtCore.QRect(10, 120, 60, 60))
        self.saveBut.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.saveBut.setStyleSheet("background:#2AC267;\n"
"border-radius:10px;")
        self.saveBut.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("media/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveBut.setIcon(icon1)
        self.saveBut.setIconSize(QtCore.QSize(40, 40))
        self.saveBut.setObjectName("saveBut")
        self.deleteBut = QtWidgets.QPushButton(bookDetailsWindow)
        self.deleteBut.setGeometry(QtCore.QRect(10, 230, 60, 60))
        self.deleteBut.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.deleteBut.setStyleSheet("background:#2AC267;\n"
"border-radius:10px;")
        self.deleteBut.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("media/trash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteBut.setIcon(icon2)
        self.deleteBut.setIconSize(QtCore.QSize(45, 45))
        self.deleteBut.setObjectName("deleteBut")
        self.label_6 = QtWidgets.QLabel(bookDetailsWindow)
        self.label_6.setGeometry(QtCore.QRect(10, 72, 60, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: #29B461;")
        self.label_7 = QtWidgets.QLabel(bookDetailsWindow)
        self.label_7.setGeometry(QtCore.QRect(10, 180, 60, 20))
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: #29B461;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(bookDetailsWindow)
        self.label_8.setGeometry(QtCore.QRect(10, 290, 60, 20))
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: #29B461;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.categoryCombo = QtWidgets.QComboBox(bookDetailsWindow)
        self.categoryCombo.setEnabled(False)
        self.categoryCombo.setGeometry(QtCore.QRect(120, 270, 421, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.categoryCombo.setFont(font)
        self.categoryCombo.setAutoFillBackground(False)
        self.categoryCombo.setStyleSheet("background:#3e8fc9;\n"
"color:white;")
        self.categoryCombo.setEditable(False)
        self.categoryCombo.setObjectName("categoryCombo")
        self.categoryCombo.addItem("")
        self.categoryCombo.addItem("")
        self.categoryCombo.addItem("")
        self.categoryCombo.addItem("")
        self.categoryCombo.addItem("")
        self.categoryCombo.addItem("")
        self.categoryCombo.addItem("")
        self.categoryCombo.addItem("")
        self.categoryCombo.addItem("")
        self.categoryCombo.addItem("")
        self.categoryCombo.addItem("")
        self.categoryCombo.addItem("")
        self.categoryCombo.addItem("")
        self.categoryCombo.addItem("")
        self.categoryCombo.addItem("")
        self.categoryCombo.addItem("")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(bookDetailsWindow)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(120, 370, 861, 221))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cover1Label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.cover1Label.setStyleSheet("background: white;")
        self.cover1Label.setText("")
        self.cover1Label.setObjectName("cover1Label")
        self.horizontalLayout_2.addWidget(self.cover1Label)
        self.cover2Label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.cover2Label.setStyleSheet("background: white;")
        self.cover2Label.setText("")
        self.cover2Label.setObjectName("cover2Label")
        self.horizontalLayout_2.addWidget(self.cover2Label)
        self.cover3Label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.cover3Label.setStyleSheet("background: white;")
        self.cover3Label.setText("")
        self.cover3Label.setObjectName("cover3Label")
        self.horizontalLayout_2.addWidget(self.cover3Label)
        self.cover4Label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.cover4Label.setStyleSheet("background: white;")
        self.cover4Label.setText("")
        self.cover4Label.setObjectName("cover4Label")
        self.horizontalLayout_2.addWidget(self.cover4Label)
        self.line = QtWidgets.QFrame(self.horizontalLayoutWidget_2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.selectedCoverLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.selectedCoverLabel.setStyleSheet("background: white;\n"
"border: 4px solid red;")
        self.selectedCoverLabel.setText("")
        self.selectedCoverLabel.setObjectName("selectedCoverLabel")
        self.horizontalLayout_2.addWidget(self.selectedCoverLabel)
        self.findCoverBut = QtWidgets.QPushButton(bookDetailsWindow)
        self.findCoverBut.setGeometry(QtCore.QRect(120, 600, 861, 28))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.findCoverBut.setFont(font)
        self.findCoverBut.setStyleSheet("background: #3e8fc9;")
        self.findCoverBut.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.findCoverBut.setObjectName("findCoverBut")

        self.retranslateUi(bookDetailsWindow)
        QtCore.QMetaObject.connectSlotsByName(bookDetailsWindow)

    def retranslateUi(self, bookDetailsWindow):
        _translate = QtCore.QCoreApplication.translate
        bookDetailsWindow.setWindowTitle(_translate("bookDetailsWindow", "Book Details"))
        self.label.setText(_translate("bookDetailsWindow", "Book Name"))
        self.label_2.setText(_translate("bookDetailsWindow", "Author Name"))
        self.label_3.setText(_translate("bookDetailsWindow", "Category"))
        self.label_4.setText(_translate("bookDetailsWindow", "Page Number"))
        self.ownCheck.setText(_translate("bookDetailsWindow", "Owned"))
        self.readCheck.setText(_translate("bookDetailsWindow", "Read"))
        self.label_6.setText(_translate("bookDetailsWindow", "Edit"))
        self.label_7.setText(_translate("bookDetailsWindow", "Save"))
        self.label_8.setText(_translate("bookDetailsWindow", "Delete"))
        self.categoryCombo.setItemText(0, _translate("bookDetailsWindow", "Academic"))
        self.categoryCombo.setItemText(1, _translate("bookDetailsWindow", "Art"))
        self.categoryCombo.setItemText(2, _translate("bookDetailsWindow", "Biography"))
        self.categoryCombo.setItemText(3, _translate("bookDetailsWindow", "Business"))
        self.categoryCombo.setItemText(4, _translate("bookDetailsWindow", "Comics"))
        self.categoryCombo.setItemText(5, _translate("bookDetailsWindow", "Economics"))
        self.categoryCombo.setItemText(6, _translate("bookDetailsWindow", "Essay"))
        self.categoryCombo.setItemText(7, _translate("bookDetailsWindow", "History"))
        self.categoryCombo.setItemText(8, _translate("bookDetailsWindow", "Law"))
        self.categoryCombo.setItemText(9, _translate("bookDetailsWindow", "Novel"))
        self.categoryCombo.setItemText(10, _translate("bookDetailsWindow", "Personal Evolution"))
        self.categoryCombo.setItemText(11, _translate("bookDetailsWindow", "Philosophy"))
        self.categoryCombo.setItemText(12, _translate("bookDetailsWindow", "Poetry"))
        self.categoryCombo.setItemText(13, _translate("bookDetailsWindow", "Politics"))
        self.categoryCombo.setItemText(14, _translate("bookDetailsWindow", "Religion"))
        self.categoryCombo.setItemText(15, _translate("bookDetailsWindow", "Science"))
        self.categoryCombo.setItemText(16, _translate("bookDetailsWindow", "Turkish Literature"))
        self.categoryCombo.setItemText(17, _translate("bookDetailsWindow", "World Literature"))
        self.findCoverBut.setText(_translate("bookDetailsWindow", "Find a new image!"))