# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1352, 758)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("media/Logom2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setStyleSheet("background:#3e8fc9;")
        self.frame = QtWidgets.QFrame(mainWindow)
        self.frame.setGeometry(QtCore.QRect(175, 90, 1000, 651))
        self.frame.setStyleSheet("background:#ef233c;\n"
"border-radius:30px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 10, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.cat_name_label = QtWidgets.QLabel(self.frame)
        self.cat_name_label.setGeometry(QtCore.QRect(110, 10, 601, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.cat_name_label.setFont(font)
        self.cat_name_label.setStyleSheet("color:white;")
        self.cat_name_label.setText("")
        self.cat_name_label.setObjectName("cat_name_label")
        self.sorter = QtWidgets.QComboBox(self.frame)
        self.sorter.setGeometry(QtCore.QRect(740, 10, 231, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sorter.setFont(font)
        self.sorter.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sorter.setMouseTracking(False)
        self.sorter.setStyleSheet("background:white;")
        self.sorter.setObjectName("sorter")
        self.sorter.addItem("")
        self.sorter.addItem("")
        self.sorter.addItem("")
        self.sorter.addItem("")
        self.sorter.addItem("")
        self.sorter.addItem("")
        self.sorter.addItem("")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(90, 610, 861, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.book_count_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.book_count_label.setFont(font)
        self.book_count_label.setStyleSheet("color:white;")
        self.book_count_label.setText("")
        self.book_count_label.setObjectName("book_count_label")
        self.horizontalLayout.addWidget(self.book_count_label)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.owned_count_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.owned_count_label.setFont(font)
        self.owned_count_label.setStyleSheet("color:white;")
        self.owned_count_label.setText("")
        self.owned_count_label.setObjectName("owned_count_label")
        self.horizontalLayout.addWidget(self.owned_count_label)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.read_count_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.read_count_label.setFont(font)
        self.read_count_label.setStyleSheet("color:white;")
        self.read_count_label.setText("")
        self.read_count_label.setObjectName("read_count_label")
        self.horizontalLayout.addWidget(self.read_count_label)
        self.listWidget = QtWidgets.QListWidget(self.frame)
        self.listWidget.setGeometry(QtCore.QRect(0, 40, 10001, 571))
        self.listWidget.setStyleSheet("background:white;\n"
"border-radius:0px;")
        self.listWidget.setObjectName("listWidget")
        self.frame_2 = QtWidgets.QFrame(mainWindow)
        self.frame_2.setGeometry(QtCore.QRect(175, 20, 1000, 50))
        self.frame_2.setStyleSheet("background:white;\n"
"border-radius:25px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.search_but = QtWidgets.QPushButton(self.frame_2)
        self.search_but.setGeometry(QtCore.QRect(940, 7, 36, 36))
        self.search_but.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.search_but.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("media/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_but.setIcon(icon1)
        self.search_but.setIconSize(QtCore.QSize(36, 36))
        self.search_but.setObjectName("search_but")
        self.search_box = QtWidgets.QLineEdit(self.frame_2)
        self.search_box.setGeometry(QtCore.QRect(30, 1, 881, 48))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.search_box.setFont(font)
        self.search_box.setText("")
        self.search_box.setObjectName("search_box")
        self.frame_3 = QtWidgets.QFrame(mainWindow)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 161, 758))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.frame_3.setFont(font)
        self.frame_3.setStyleSheet("background:#80c5ed;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.cat_academic = QtWidgets.QPushButton(self.frame_3)
        self.cat_academic.setGeometry(QtCore.QRect(0, 78, 161, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cat_academic.setFont(font)
        self.cat_academic.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cat_academic.setStyleSheet("background:#f1faee;\n"
"border:0px;")
        self.cat_academic.setObjectName("cat_academic")
        self.cat_art = QtWidgets.QPushButton(self.frame_3)
        self.cat_art.setGeometry(QtCore.QRect(0, 116, 161, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cat_art.setFont(font)
        self.cat_art.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cat_art.setStyleSheet("background:#f1faee;\n"
"border:0px;")
        self.cat_art.setObjectName("cat_art")
        self.cat_biography = QtWidgets.QPushButton(self.frame_3)
        self.cat_biography.setGeometry(QtCore.QRect(0, 154, 161, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cat_biography.setFont(font)
        self.cat_biography.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cat_biography.setStyleSheet("background:#f1faee;\n"
"border:0px;")
        self.cat_biography.setObjectName("cat_biography")
        self.cat_business = QtWidgets.QPushButton(self.frame_3)
        self.cat_business.setGeometry(QtCore.QRect(0, 192, 161, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cat_business.setFont(font)
        self.cat_business.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cat_business.setStyleSheet("background:#f1faee;\n"
"border:0px;")
        self.cat_business.setObjectName("cat_business")
        self.cat_economics = QtWidgets.QPushButton(self.frame_3)
        self.cat_economics.setGeometry(QtCore.QRect(0, 230, 161, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cat_economics.setFont(font)
        self.cat_economics.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cat_economics.setStyleSheet("background:#f1faee;\n"
"border:0px;")
        self.cat_economics.setObjectName("cat_economics")
        self.cat_history = QtWidgets.QPushButton(self.frame_3)
        self.cat_history.setGeometry(QtCore.QRect(0, 268, 161, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cat_history.setFont(font)
        self.cat_history.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cat_history.setStyleSheet("background:#f1faee;\n"
"border:0px;")
        self.cat_history.setObjectName("cat_history")
        self.cat_law = QtWidgets.QPushButton(self.frame_3)
        self.cat_law.setGeometry(QtCore.QRect(0, 306, 161, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cat_law.setFont(font)
        self.cat_law.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cat_law.setStyleSheet("background:#f1faee;\n"
"border:0px;")
        self.cat_law.setObjectName("cat_law")
        self.cat_novel = QtWidgets.QPushButton(self.frame_3)
        self.cat_novel.setGeometry(QtCore.QRect(0, 344, 161, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cat_novel.setFont(font)
        self.cat_novel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cat_novel.setStyleSheet("background:#f1faee;\n"
"border:0px;")
        self.cat_novel.setObjectName("cat_novel")
        self.cat_persev = QtWidgets.QPushButton(self.frame_3)
        self.cat_persev.setGeometry(QtCore.QRect(0, 382, 161, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cat_persev.setFont(font)
        self.cat_persev.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cat_persev.setStyleSheet("background:#f1faee;\n"
"border:0px;")
        self.cat_persev.setObjectName("cat_persev")
        self.cat_philosophy = QtWidgets.QPushButton(self.frame_3)
        self.cat_philosophy.setGeometry(QtCore.QRect(0, 420, 161, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cat_philosophy.setFont(font)
        self.cat_philosophy.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cat_philosophy.setStyleSheet("background:#f1faee;\n"
"border:0px;")
        self.cat_philosophy.setObjectName("cat_philosophy")
        self.cat_poetry = QtWidgets.QPushButton(self.frame_3)
        self.cat_poetry.setGeometry(QtCore.QRect(0, 458, 161, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cat_poetry.setFont(font)
        self.cat_poetry.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cat_poetry.setStyleSheet("background:#f1faee;\n"
"border:0px;")
        self.cat_poetry.setObjectName("cat_poetry")
        self.cat_politics = QtWidgets.QPushButton(self.frame_3)
        self.cat_politics.setGeometry(QtCore.QRect(0, 496, 161, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cat_politics.setFont(font)
        self.cat_politics.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cat_politics.setStyleSheet("background:#f1faee;\n"
"border:0px;")
        self.cat_politics.setObjectName("cat_politics")
        self.cat_religion = QtWidgets.QPushButton(self.frame_3)
        self.cat_religion.setGeometry(QtCore.QRect(0, 534, 161, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cat_religion.setFont(font)
        self.cat_religion.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cat_religion.setStyleSheet("background:#f1faee;\n"
"border:0px;")
        self.cat_religion.setObjectName("cat_religion")
        self.cat_science = QtWidgets.QPushButton(self.frame_3)
        self.cat_science.setGeometry(QtCore.QRect(0, 572, 161, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cat_science.setFont(font)
        self.cat_science.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cat_science.setStyleSheet("background:#f1faee;\n"
"border:0px;")
        self.cat_science.setObjectName("cat_science")
        self.cat_turlit = QtWidgets.QPushButton(self.frame_3)
        self.cat_turlit.setGeometry(QtCore.QRect(0, 610, 161, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cat_turlit.setFont(font)
        self.cat_turlit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cat_turlit.setStyleSheet("background:#f1faee;\n"
"border:0px;")
        self.cat_turlit.setObjectName("cat_turlit")
        self.cat_worlit = QtWidgets.QPushButton(self.frame_3)
        self.cat_worlit.setGeometry(QtCore.QRect(0, 648, 161, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cat_worlit.setFont(font)
        self.cat_worlit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cat_worlit.setStyleSheet("background:#f1faee;\n"
"border:0px;")
        self.cat_worlit.setObjectName("cat_worlit")
        self.cat_research = QtWidgets.QPushButton(self.frame_3)
        self.cat_research.setGeometry(QtCore.QRect(0, 686, 161, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cat_research.setFont(font)
        self.cat_research.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cat_research.setStyleSheet("background:#3174a3;\n"
"color:white;\n"
"border:0px;")
        self.cat_research.setObjectName("cat_research")
        self.cat_allbooks = QtWidgets.QPushButton(self.frame_3)
        self.cat_allbooks.setGeometry(QtCore.QRect(0, 40, 161, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cat_allbooks.setFont(font)
        self.cat_allbooks.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cat_allbooks.setStyleSheet("background:#3174a3;\n"
"color:white;\n"
"border:0px;")
        self.cat_allbooks.setObjectName("cat_allbooks")
        self.frame_4 = QtWidgets.QFrame(mainWindow)
        self.frame_4.setGeometry(QtCore.QRect(1190, 0, 162, 758))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.frame_4.setFont(font)
        self.frame_4.setStyleSheet("background:#80c5ed;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.add_book_but = QtWidgets.QPushButton(self.frame_4)
        self.add_book_but.setGeometry(QtCore.QRect(10, 75, 130, 121))
        self.add_book_but.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_book_but.setStyleSheet("border:0px;")
        self.add_book_but.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("media/add_book.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_book_but.setIcon(icon2)
        self.add_book_but.setIconSize(QtCore.QSize(121, 121))
        self.add_book_but.setObjectName("add_book_but")
        self.label_10 = QtWidgets.QLabel(self.frame_4)
        self.label_10.setGeometry(QtCore.QRect(50, 206, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.random_book_but = QtWidgets.QPushButton(self.frame_4)
        self.random_book_but.setGeometry(QtCore.QRect(12, 302, 130, 121))
        self.random_book_but.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.random_book_but.setStyleSheet("border:0px;")
        self.random_book_but.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("media/random.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.random_book_but.setIcon(icon3)
        self.random_book_but.setIconSize(QtCore.QSize(110, 110))
        self.random_book_but.setObjectName("random_book_but")
        self.label_11 = QtWidgets.QLabel(self.frame_4)
        self.label_11.setGeometry(QtCore.QRect(30, 433, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.statistics_but = QtWidgets.QPushButton(self.frame_4)
        self.statistics_but.setGeometry(QtCore.QRect(20, 529, 130, 121))
        self.statistics_but.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.statistics_but.setStyleSheet("border:0px;")
        self.statistics_but.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("media/research.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.statistics_but.setIcon(icon4)
        self.statistics_but.setIconSize(QtCore.QSize(110, 110))
        self.statistics_but.setObjectName("statistics_but")
        self.label_12 = QtWidgets.QLabel(self.frame_4)
        self.label_12.setGeometry(QtCore.QRect(50, 660, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Atalib III"))
        self.label.setText(_translate("mainWindow", "Category:"))
        self.sorter.setCurrentText(_translate("mainWindow", "A>Z (Book Name)"))
        self.sorter.setItemText(0, _translate("mainWindow", "A>Z (Book Name)"))
        self.sorter.setItemText(1, _translate("mainWindow", "Z>A (Book Name)"))
        self.sorter.setItemText(2, _translate("mainWindow", "A>Z (Author Name)"))
        self.sorter.setItemText(3, _translate("mainWindow", "Z>A (Author Name)"))
        self.sorter.setItemText(4, _translate("mainWindow", "Page Count"))
        self.sorter.setItemText(5, _translate("mainWindow", "Owned Books"))
        self.sorter.setItemText(6, _translate("mainWindow", "Read Books"))
        self.label_3.setText(_translate("mainWindow", "Book Count:"))
        self.label_5.setText(_translate("mainWindow", "Owned Count:"))
        self.label_8.setText(_translate("mainWindow", "Read Count:"))
        self.search_box.setPlaceholderText(_translate("mainWindow", "Search a book name or an author"))
        self.cat_academic.setText(_translate("mainWindow", "Academic"))
        self.cat_art.setText(_translate("mainWindow", "Art"))
        self.cat_biography.setText(_translate("mainWindow", "Biography"))
        self.cat_business.setText(_translate("mainWindow", "Business"))
        self.cat_economics.setText(_translate("mainWindow", "Economics"))
        self.cat_history.setText(_translate("mainWindow", "History"))
        self.cat_law.setText(_translate("mainWindow", "Law"))
        self.cat_novel.setText(_translate("mainWindow", "Novel"))
        self.cat_persev.setText(_translate("mainWindow", "Personal Evolution"))
        self.cat_philosophy.setText(_translate("mainWindow", "Philosophy"))
        self.cat_poetry.setText(_translate("mainWindow", "Poetry"))
        self.cat_politics.setText(_translate("mainWindow", "Politics"))
        self.cat_religion.setText(_translate("mainWindow", "Religion"))
        self.cat_science.setText(_translate("mainWindow", "Science"))
        self.cat_turlit.setText(_translate("mainWindow", "Turkish Literature"))
        self.cat_worlit.setText(_translate("mainWindow", "World Literature"))
        self.cat_research.setText(_translate("mainWindow", "Reserach"))
        self.cat_allbooks.setText(_translate("mainWindow", "All Books"))
        self.label_10.setText(_translate("mainWindow", "Add Book"))
        self.label_11.setText(_translate("mainWindow", "Random Book"))
        self.label_12.setText(_translate("mainWindow", "Statistics"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QWidget()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
