# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addBook.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_addBookWindow(object):
    def setupUi(self, addBookWindow):
        addBookWindow.setObjectName("addBookWindow")
        addBookWindow.resize(997, 418)
        addBookWindow.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("media/Logom2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        addBookWindow.setWindowIcon(icon)
        addBookWindow.setStyleSheet("background:#80c5ed;")
        self.label = QtWidgets.QLabel(addBookWindow)
        self.label.setGeometry(QtCore.QRect(120, 20, 861, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(addBookWindow)
        self.label_2.setGeometry(QtCore.QRect(120, 120, 861, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.book_name_label = QtWidgets.QLineEdit(addBookWindow)
        self.book_name_label.setEnabled(True)
        self.book_name_label.setGeometry(QtCore.QRect(120, 60, 861, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(10)
        font.setItalic(False)
        self.book_name_label.setFont(font)
        self.book_name_label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.book_name_label.setStyleSheet("background:white;\n"
"border:0px;")
        self.book_name_label.setText("")
        self.book_name_label.setReadOnly(False)
        self.book_name_label.setClearButtonEnabled(False)
        self.book_name_label.setObjectName("book_name_label")
        self.author_name_label = QtWidgets.QLineEdit(addBookWindow)
        self.author_name_label.setGeometry(QtCore.QRect(120, 160, 861, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(10)
        font.setItalic(False)
        self.author_name_label.setFont(font)
        self.author_name_label.setStyleSheet("background:white;\n"
"border:0px;")
        self.author_name_label.setText("")
        self.author_name_label.setReadOnly(False)
        self.author_name_label.setObjectName("author_name_label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(addBookWindow)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(120, 210, 861, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.page_label = QtWidgets.QLineEdit(addBookWindow)
        self.page_label.setGeometry(QtCore.QRect(560, 270, 421, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(10)
        font.setItalic(False)
        self.page_label.setFont(font)
        self.page_label.setStyleSheet("background:white;\n"
"border:0px;")
        self.page_label.setText("")
        self.page_label.setReadOnly(False)
        self.page_label.setObjectName("page_label")
        self.owned_check = QtWidgets.QCheckBox(addBookWindow)
        self.owned_check.setGeometry(QtCore.QRect(120, 320, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.owned_check.setFont(font)
        self.owned_check.setObjectName("owned_check")
        self.read_check = QtWidgets.QCheckBox(addBookWindow)
        self.read_check.setGeometry(QtCore.QRect(120, 370, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.read_check.setFont(font)
        self.read_check.setObjectName("read_check")
        self.add_but = QtWidgets.QPushButton(addBookWindow)
        self.add_but.setGeometry(QtCore.QRect(10, 120, 60, 60))
        self.add_but.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_but.setStyleSheet("background:#f1faee;\n"
"border-radius:10px;")
        self.add_but.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("media/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_but.setIcon(icon1)
        self.add_but.setIconSize(QtCore.QSize(40, 40))
        self.add_but.setObjectName("add_but")
        self.cancel_but = QtWidgets.QPushButton(addBookWindow)
        self.cancel_but.setGeometry(QtCore.QRect(10, 230, 60, 60))
        self.cancel_but.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel_but.setStyleSheet("background:#f1faee;\n"
"border-radius:10px;")
        self.cancel_but.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("media/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancel_but.setIcon(icon2)
        self.cancel_but.setIconSize(QtCore.QSize(40, 40))
        self.cancel_but.setObjectName("cancel_but")
        self.label_7 = QtWidgets.QLabel(addBookWindow)
        self.label_7.setGeometry(QtCore.QRect(10, 180, 60, 20))
        self.label_7.setStyleSheet("color:white;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(addBookWindow)
        self.label_8.setGeometry(QtCore.QRect(10, 290, 60, 20))
        self.label_8.setStyleSheet("color:white;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.cat_combo = QtWidgets.QComboBox(addBookWindow)
        self.cat_combo.setEnabled(True)
        self.cat_combo.setGeometry(QtCore.QRect(120, 270, 421, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.cat_combo.setFont(font)
        self.cat_combo.setAutoFillBackground(False)
        self.cat_combo.setStyleSheet("background:#3e8fc9;\n"
"color:white;")
        self.cat_combo.setEditable(False)
        self.cat_combo.setObjectName("cat_combo")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")

        self.retranslateUi(addBookWindow)
        QtCore.QMetaObject.connectSlotsByName(addBookWindow)

    def retranslateUi(self, addBookWindow):
        _translate = QtCore.QCoreApplication.translate
        addBookWindow.setWindowTitle(_translate("addBookWindow", "Add Book"))
        self.label.setText(_translate("addBookWindow", "Book Name"))
        self.label_2.setText(_translate("addBookWindow", "Author Name"))
        self.book_name_label.setPlaceholderText(_translate("addBookWindow", "Type the book\'s name here"))
        self.author_name_label.setPlaceholderText(_translate("addBookWindow", "Type the author(s)\'s name here"))
        self.label_3.setText(_translate("addBookWindow", "Category"))
        self.label_4.setText(_translate("addBookWindow", "Page Number"))
        self.page_label.setPlaceholderText(_translate("addBookWindow", "Type page number here"))
        self.owned_check.setText(_translate("addBookWindow", "Owned"))
        self.read_check.setText(_translate("addBookWindow", "Read"))
        self.label_7.setText(_translate("addBookWindow", "Add"))
        self.label_8.setText(_translate("addBookWindow", "Cancel"))
        self.cat_combo.setItemText(0, _translate("addBookWindow", "Choose a category"))
        self.cat_combo.setItemText(1, _translate("addBookWindow", "Academic"))
        self.cat_combo.setItemText(2, _translate("addBookWindow", "Art"))
        self.cat_combo.setItemText(3, _translate("addBookWindow", "Biography"))
        self.cat_combo.setItemText(4, _translate("addBookWindow", "Business"))
        self.cat_combo.setItemText(5, _translate("addBookWindow", "Economics"))
        self.cat_combo.setItemText(6, _translate("addBookWindow", "History"))
        self.cat_combo.setItemText(7, _translate("addBookWindow", "Law"))
        self.cat_combo.setItemText(8, _translate("addBookWindow", "Novel"))
        self.cat_combo.setItemText(9, _translate("addBookWindow", "Personal Evolution"))
        self.cat_combo.setItemText(10, _translate("addBookWindow", "Philosophy"))
        self.cat_combo.setItemText(11, _translate("addBookWindow", "Poetry"))
        self.cat_combo.setItemText(12, _translate("addBookWindow", "Politics"))
        self.cat_combo.setItemText(13, _translate("addBookWindow", "Religion"))
        self.cat_combo.setItemText(14, _translate("addBookWindow", "Science"))
        self.cat_combo.setItemText(15, _translate("addBookWindow", "Turkish Literature"))
        self.cat_combo.setItemText(16, _translate("addBookWindow", "World Literature"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addBookWindow = QtWidgets.QWidget()
    ui = Ui_addBookWindow()
    ui.setupUi(addBookWindow)
    addBookWindow.show()
    sys.exit(app.exec_())
