# -*- coding: utf-8 -*-

# Created by Atahan Caldir

from PyQt5 import QtCore, QtGui, QtWidgets
import sys

yellow = QtGui.QBrush(QtCore.Qt.yellow)
green = QtGui.QBrush(QtCore.Qt.green)

class Ui_mainWindow(QtWidgets.QWidget):

    def __init__(self):
        QtWidgets.QWidget.__init__(self)
        self.setupUi(self)

    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.setFixedSize(1352, 758)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("media/Logom2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setStyleSheet("background:#3e8fc9;")
        self.frame = QtWidgets.QFrame(mainWindow)
        self.frame.setGeometry(QtCore.QRect(175, 90, 1000, 651))
        self.frame.setStyleSheet("background:#ef233c;\n"
"border-radius:10px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 10, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.cat_name_label = QtWidgets.QLabel(self.frame)
        self.cat_name_label.setGeometry(QtCore.QRect(110, 10, 601, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.cat_name_label.setFont(font)
        self.cat_name_label.setStyleSheet("color:white;")
        self.cat_name_label.setText("")
        self.cat_name_label.setObjectName("cat_name_label")
        self.sorter = QtWidgets.QComboBox(self.frame)
        self.sorter.setGeometry(QtCore.QRect(740, 10, 231, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sorter.setFont(font)
        self.sorter.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sorter.setMouseTracking(False)
        self.sorter.setStyleSheet("background:white;\n"
"border-radius:0px;\n")
        self.sorter.setObjectName("sorter")
        self.sorter.addItem("")
        self.sorter.addItem("")
        self.sorter.addItem("")
        self.sorter.addItem("")
        self.sorter.addItem("")
        self.sorter.addItem("")
        self.sorter.addItem("")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(90, 610, 861, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.book_count_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.book_count_label.setFont(font)
        self.book_count_label.setStyleSheet("color:white;")
        self.book_count_label.setText("")
        self.book_count_label.setObjectName("book_count_label")
        self.horizontalLayout.addWidget(self.book_count_label)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.owned_count_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.owned_count_label.setFont(font)
        self.owned_count_label.setStyleSheet("color:white;")
        self.owned_count_label.setText("")
        self.owned_count_label.setObjectName("owned_count_label")
        self.horizontalLayout.addWidget(self.owned_count_label)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.read_count_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.read_count_label.setFont(font)
        self.read_count_label.setStyleSheet("color:white;")
        self.read_count_label.setText("")
        self.read_count_label.setObjectName("read_count_label")
        self.horizontalLayout.addWidget(self.read_count_label)
        self.book_list = QtWidgets.QListWidget(self.frame)
        self.book_list.setGeometry(QtCore.QRect(0, 40, 10001, 571))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.book_list.setFont(font)
        self.book_list.setStyleSheet("background:white;\n"
"border-radius:0px;")
        self.book_list.setObjectName("book_list")
        self.frame_2 = QtWidgets.QFrame(mainWindow)
        self.frame_2.setGeometry(QtCore.QRect(175, 20, 1000, 50))
        self.frame_2.setStyleSheet("background:white;\n"
"border-radius:25px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.search_but = QtWidgets.QPushButton(self.frame_2)
        self.search_but.setGeometry(QtCore.QRect(940, 7, 36, 36))
        self.search_but.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.search_but.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("media/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_but.setIcon(icon1)
        self.search_but.setIconSize(QtCore.QSize(36, 36))
        self.search_but.setObjectName("search_but")
        self.search_box = QtWidgets.QLineEdit(self.frame_2)
        self.search_box.setGeometry(QtCore.QRect(30, 1, 881, 48))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.search_box.setFont(font)
        self.search_box.setText("")
        self.search_box.setObjectName("search_box")
        self.frame_3 = QtWidgets.QFrame(mainWindow)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 161, 758))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.frame_3.setFont(font)
        self.frame_3.setStyleSheet("background:#80c5ed;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.cat_academic = QtWidgets.QPushButton(self.frame_3)
        self.cat_academic.setGeometry(QtCore.QRect(0, 78, 161, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cat_academic.setFont(font)
        self.cat_academic.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cat_academic.setStyleSheet("background:#f1faee;\n"
"border:0px;")
        self.cat_academic.setObjectName("cat_academic")
        self.cat_art = QtWidgets.QPushButton(self.frame_3)
        self.cat_art.setGeometry(QtCore.QRect(0, 116, 161, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cat_art.setFont(font)
        self.cat_art.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cat_art.setStyleSheet("background:#f1faee;\n"
"border:0px;")
        self.cat_art.setObjectName("cat_art")
        self.cat_biography = QtWidgets.QPushButton(self.frame_3)
        self.cat_biography.setGeometry(QtCore.QRect(0, 154, 161, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cat_biography.setFont(font)
        self.cat_biography.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cat_biography.setStyleSheet("background:#f1faee;\n"
"border:0px;")
        self.cat_biography.setObjectName("cat_biography")
        self.cat_business = QtWidgets.QPushButton(self.frame_3)
        self.cat_business.setGeometry(QtCore.QRect(0, 192, 161, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cat_business.setFont(font)
        self.cat_business.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cat_business.setStyleSheet("background:#f1faee;\n"
"border:0px;")
        self.cat_business.setObjectName("cat_business")
        self.cat_economics = QtWidgets.QPushButton(self.frame_3)
        self.cat_economics.setGeometry(QtCore.QRect(0, 230, 161, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cat_economics.setFont(font)
        self.cat_economics.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cat_economics.setStyleSheet("background:#f1faee;\n"
"border:0px;")
        self.cat_economics.setObjectName("cat_economics")
        self.cat_history = QtWidgets.QPushButton(self.frame_3)
        self.cat_history.setGeometry(QtCore.QRect(0, 268, 161, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cat_history.setFont(font)
        self.cat_history.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cat_history.setStyleSheet("background:#f1faee;\n"
"border:0px;")
        self.cat_history.setObjectName("cat_history")
        self.cat_law = QtWidgets.QPushButton(self.frame_3)
        self.cat_law.setGeometry(QtCore.QRect(0, 306, 161, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cat_law.setFont(font)
        self.cat_law.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cat_law.setStyleSheet("background:#f1faee;\n"
"border:0px;")
        self.cat_law.setObjectName("cat_law")
        self.cat_novel = QtWidgets.QPushButton(self.frame_3)
        self.cat_novel.setGeometry(QtCore.QRect(0, 344, 161, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cat_novel.setFont(font)
        self.cat_novel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cat_novel.setStyleSheet("background:#f1faee;\n"
"border:0px;")
        self.cat_novel.setObjectName("cat_novel")
        self.cat_persev = QtWidgets.QPushButton(self.frame_3)
        self.cat_persev.setGeometry(QtCore.QRect(0, 382, 161, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cat_persev.setFont(font)
        self.cat_persev.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cat_persev.setStyleSheet("background:#f1faee;\n"
"border:0px;")
        self.cat_persev.setObjectName("cat_persev")
        self.cat_philosophy = QtWidgets.QPushButton(self.frame_3)
        self.cat_philosophy.setGeometry(QtCore.QRect(0, 420, 161, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cat_philosophy.setFont(font)
        self.cat_philosophy.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cat_philosophy.setStyleSheet("background:#f1faee;\n"
"border:0px;")
        self.cat_philosophy.setObjectName("cat_philosophy")
        self.cat_poetry = QtWidgets.QPushButton(self.frame_3)
        self.cat_poetry.setGeometry(QtCore.QRect(0, 458, 161, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cat_poetry.setFont(font)
        self.cat_poetry.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cat_poetry.setStyleSheet("background:#f1faee;\n"
"border:0px;")
        self.cat_poetry.setObjectName("cat_poetry")
        self.cat_politics = QtWidgets.QPushButton(self.frame_3)
        self.cat_politics.setGeometry(QtCore.QRect(0, 496, 161, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cat_politics.setFont(font)
        self.cat_politics.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cat_politics.setStyleSheet("background:#f1faee;\n"
"border:0px;")
        self.cat_politics.setObjectName("cat_politics")
        self.cat_religion = QtWidgets.QPushButton(self.frame_3)
        self.cat_religion.setGeometry(QtCore.QRect(0, 534, 161, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cat_religion.setFont(font)
        self.cat_religion.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cat_religion.setStyleSheet("background:#f1faee;\n"
"border:0px;")
        self.cat_religion.setObjectName("cat_religion")
        self.cat_science = QtWidgets.QPushButton(self.frame_3)
        self.cat_science.setGeometry(QtCore.QRect(0, 572, 161, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cat_science.setFont(font)
        self.cat_science.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cat_science.setStyleSheet("background:#f1faee;\n"
"border:0px;")
        self.cat_science.setObjectName("cat_science")
        self.cat_turlit = QtWidgets.QPushButton(self.frame_3)
        self.cat_turlit.setGeometry(QtCore.QRect(0, 610, 161, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cat_turlit.setFont(font)
        self.cat_turlit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cat_turlit.setStyleSheet("background:#f1faee;\n"
"border:0px;")
        self.cat_turlit.setObjectName("cat_turlit")
        self.cat_worlit = QtWidgets.QPushButton(self.frame_3)
        self.cat_worlit.setGeometry(QtCore.QRect(0, 648, 161, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cat_worlit.setFont(font)
        self.cat_worlit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cat_worlit.setStyleSheet("background:#f1faee;\n"
"border:0px;")
        self.cat_worlit.setObjectName("cat_worlit")
        self.cat_research = QtWidgets.QPushButton(self.frame_3)
        self.cat_research.setGeometry(QtCore.QRect(0, 686, 161, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cat_research.setFont(font)
        self.cat_research.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cat_research.setStyleSheet("background:#3174a3;\n"
"color:white;\n"
"border:0px;")
        self.cat_research.setObjectName("cat_research")
        self.cat_allbooks = QtWidgets.QPushButton(self.frame_3)
        self.cat_allbooks.setGeometry(QtCore.QRect(0, 40, 161, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cat_allbooks.setFont(font)
        self.cat_allbooks.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cat_allbooks.setStyleSheet("background:#3174a3;\n"
"color:white;\n"
"border:0px;")
        self.cat_allbooks.setObjectName("cat_allbooks")
        self.frame_4 = QtWidgets.QFrame(mainWindow)
        self.frame_4.setGeometry(QtCore.QRect(1190, 0, 162, 758))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.frame_4.setFont(font)
        self.frame_4.setStyleSheet("background:#80c5ed;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.add_book_but = QtWidgets.QPushButton(self.frame_4)
        self.add_book_but.setGeometry(QtCore.QRect(10, 75, 130, 121))
        self.add_book_but.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_book_but.setStyleSheet("border:0px;")
        self.add_book_but.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("media/add_book.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_book_but.setIcon(icon2)
        self.add_book_but.setIconSize(QtCore.QSize(121, 121))
        self.add_book_but.setObjectName("add_book_but")
        self.label_10 = QtWidgets.QLabel(self.frame_4)
        self.label_10.setGeometry(QtCore.QRect(50, 206, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.random_book_but = QtWidgets.QPushButton(self.frame_4)
        self.random_book_but.setGeometry(QtCore.QRect(12, 302, 130, 121))
        self.random_book_but.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.random_book_but.setStyleSheet("border:0px;")
        self.random_book_but.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("media/random.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.random_book_but.setIcon(icon3)
        self.random_book_but.setIconSize(QtCore.QSize(110, 110))
        self.random_book_but.setObjectName("random_book_but")
        self.label_11 = QtWidgets.QLabel(self.frame_4)
        self.label_11.setGeometry(QtCore.QRect(30, 433, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.statistics_but = QtWidgets.QPushButton(self.frame_4)
        self.statistics_but.setGeometry(QtCore.QRect(20, 529, 130, 121))
        self.statistics_but.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.statistics_but.setStyleSheet("border:0px;")
        self.statistics_but.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("media/research.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.statistics_but.setIcon(icon4)
        self.statistics_but.setIconSize(QtCore.QSize(110, 110))
        self.statistics_but.setObjectName("statistics_but")
        self.label_12 = QtWidgets.QLabel(self.frame_4)
        self.label_12.setGeometry(QtCore.QRect(50, 660, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Atalib III"))
        self.label.setText(_translate("mainWindow", "Category:"))
        self.sorter.setCurrentText(_translate("mainWindow", "A>Z (Book Name)"))
        self.sorter.setItemText(0, _translate("mainWindow", "A>Z (Book Name)"))
        self.sorter.setItemText(1, _translate("mainWindow", "Z>A (Book Name)"))
        self.sorter.setItemText(2, _translate("mainWindow", "A>Z (Author Name)"))
        self.sorter.setItemText(3, _translate("mainWindow", "Z>A (Author Name)"))
        self.sorter.setItemText(4, _translate("mainWindow", "Page Count"))
        self.sorter.setItemText(5, _translate("mainWindow", "Owned Books"))
        self.sorter.setItemText(6, _translate("mainWindow", "Read Books"))
        self.label_3.setText(_translate("mainWindow", "Book Count:"))
        self.label_5.setText(_translate("mainWindow", "Owned Count:"))
        self.label_8.setText(_translate("mainWindow", "Read Count:"))
        self.search_box.setPlaceholderText(_translate("mainWindow", "Search a book name or an author"))
        self.cat_academic.setText(_translate("mainWindow", "Academic"))
        self.cat_art.setText(_translate("mainWindow", "Art"))
        self.cat_biography.setText(_translate("mainWindow", "Biography"))
        self.cat_business.setText(_translate("mainWindow", "Business"))
        self.cat_economics.setText(_translate("mainWindow", "Economics"))
        self.cat_history.setText(_translate("mainWindow", "History"))
        self.cat_law.setText(_translate("mainWindow", "Law"))
        self.cat_novel.setText(_translate("mainWindow", "Novel"))
        self.cat_persev.setText(_translate("mainWindow", "Personal Evolution"))
        self.cat_philosophy.setText(_translate("mainWindow", "Philosophy"))
        self.cat_poetry.setText(_translate("mainWindow", "Poetry"))
        self.cat_politics.setText(_translate("mainWindow", "Politics"))
        self.cat_religion.setText(_translate("mainWindow", "Religion"))
        self.cat_science.setText(_translate("mainWindow", "Science"))
        self.cat_turlit.setText(_translate("mainWindow", "Turkish Literature"))
        self.cat_worlit.setText(_translate("mainWindow", "World Literature"))
        self.cat_research.setText(_translate("mainWindow", "Reserach"))
        self.cat_allbooks.setText(_translate("mainWindow", "All Books"))
        self.label_10.setText(_translate("mainWindow", "Add Book"))
        self.label_11.setText(_translate("mainWindow", "Random Book"))
        self.label_12.setText(_translate("mainWindow", "Statistics"))

class Ui_addBookWindow(QtWidgets.QWidget):

    def __init__(self):
        QtWidgets.QWidget.__init__(self)
        self.setupUi(self)

    def setupUi(self, addBookWindow):
        addBookWindow.setObjectName("addBookWindow")
        addBookWindow.setFixedSize(997, 418)
        addBookWindow.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("media/Logom2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        addBookWindow.setWindowIcon(icon)
        addBookWindow.setStyleSheet("background:#80c5ed;")
        self.label = QtWidgets.QLabel(addBookWindow)
        self.label.setGeometry(QtCore.QRect(120, 20, 861, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(addBookWindow)
        self.label_2.setGeometry(QtCore.QRect(120, 120, 861, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.book_name_label = QtWidgets.QLineEdit(addBookWindow)
        self.book_name_label.setEnabled(True)
        self.book_name_label.setGeometry(QtCore.QRect(120, 60, 861, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(10)
        font.setItalic(False)
        self.book_name_label.setFont(font)
        self.book_name_label.setStyleSheet("background:white;\n"
"border:0px;")
        self.book_name_label.setText("")
        self.book_name_label.setReadOnly(False)
        self.book_name_label.setClearButtonEnabled(False)
        self.book_name_label.setObjectName("book_name_label")
        self.author_name_label = QtWidgets.QLineEdit(addBookWindow)
        self.author_name_label.setGeometry(QtCore.QRect(120, 160, 861, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(10)
        font.setItalic(False)
        self.author_name_label.setFont(font)
        self.author_name_label.setStyleSheet("background:white;\n"
"border:0px;")
        self.author_name_label.setText("")
        self.author_name_label.setReadOnly(False)
        self.author_name_label.setObjectName("author_name_label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(addBookWindow)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(120, 210, 861, 63))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.page_label = QtWidgets.QLineEdit(addBookWindow)
        self.page_label.setGeometry(QtCore.QRect(560, 270, 421, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(10)
        font.setItalic(False)
        self.page_label.setFont(font)
        self.page_label.setStyleSheet("background:white;\n"
"border:0px;")
        self.page_label.setText("")
        self.page_label.setReadOnly(False)
        self.page_label.setObjectName("page_label")
        self.owned_check = QtWidgets.QCheckBox(addBookWindow)
        self.owned_check.setGeometry(QtCore.QRect(120, 320, 120, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(15)
        self.owned_check.setFont(font)
        self.owned_check.setObjectName("owned_check")
        self.read_check = QtWidgets.QCheckBox(addBookWindow)
        self.read_check.setGeometry(QtCore.QRect(120, 370, 120, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(15)
        self.read_check.setFont(font)
        self.read_check.setObjectName("read_check")
        self.add_but = QtWidgets.QPushButton(addBookWindow)
        self.add_but.setGeometry(QtCore.QRect(10, 120, 60, 60))
        self.add_but.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_but.setStyleSheet("background:#f1faee;\n"
"border-radius:10px;")
        self.add_but.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("media/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_but.setIcon(icon1)
        self.add_but.setIconSize(QtCore.QSize(40, 40))
        self.add_but.setObjectName("add_but")
        self.cancel_but = QtWidgets.QPushButton(addBookWindow)
        self.cancel_but.setGeometry(QtCore.QRect(10, 230, 60, 60))
        self.cancel_but.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel_but.setStyleSheet("background:#f1faee;\n"
"border-radius:10px;")
        self.cancel_but.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("media/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancel_but.setIcon(icon2)
        self.cancel_but.setIconSize(QtCore.QSize(40, 40))
        self.cancel_but.setObjectName("cancel_but")
        self.label_7 = QtWidgets.QLabel(addBookWindow)
        self.label_7.setGeometry(QtCore.QRect(10, 180, 60, 20))
        self.label_7.setStyleSheet("color:white;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(addBookWindow)
        self.label_8.setGeometry(QtCore.QRect(10, 290, 60, 20))
        self.label_8.setStyleSheet("color:white;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.cat_combo = QtWidgets.QComboBox(addBookWindow)
        self.cat_combo.setEnabled(True)
        self.cat_combo.setGeometry(QtCore.QRect(120, 270, 421, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.cat_combo.setFont(font)
        self.cat_combo.setAutoFillBackground(False)
        self.cat_combo.setStyleSheet("background:#3e8fc9;\n"
"color:white;")
        self.cat_combo.setEditable(False)
        self.cat_combo.setObjectName("cat_combo")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")

        self.retranslateUi(addBookWindow)
        QtCore.QMetaObject.connectSlotsByName(addBookWindow)

    def closeEvent(self, event):
        self.book_name_label.setText("")
        self.author_name_label.setText("")
        self.page_label.setText("")
        self.cat_combo.setCurrentIndex(0)
        self.owned_check.setChecked(False)
        self.read_check.setChecked(False)

    def retranslateUi(self, addBookWindow):
        _translate = QtCore.QCoreApplication.translate
        addBookWindow.setWindowTitle(_translate("addBookWindow", "Add Book"))
        self.label.setText(_translate("addBookWindow", "Book Name"))
        self.label_2.setText(_translate("addBookWindow", "Author Name"))
        self.book_name_label.setPlaceholderText(_translate("addBookWindow", "Type the book\'s name here"))
        self.author_name_label.setPlaceholderText(_translate("addBookWindow", "Type the author(s)\'s name here"))
        self.label_3.setText(_translate("addBookWindow", "Category"))
        self.label_4.setText(_translate("addBookWindow", "Page Number"))
        self.page_label.setPlaceholderText(_translate("addBookWindow", "Type page number here"))
        self.owned_check.setText(_translate("addBookWindow", "Owned"))
        self.read_check.setText(_translate("addBookWindow", "Read"))
        self.label_7.setText(_translate("addBookWindow", "Add"))
        self.label_8.setText(_translate("addBookWindow", "Cancel"))
        self.cat_combo.setItemText(0, _translate("addBookWindow", "Choose a category"))
        self.cat_combo.setItemText(1, _translate("addBookWindow", "Academic"))
        self.cat_combo.setItemText(2, _translate("addBookWindow", "Art"))
        self.cat_combo.setItemText(3, _translate("addBookWindow", "Biography"))
        self.cat_combo.setItemText(4, _translate("addBookWindow", "Business"))
        self.cat_combo.setItemText(5, _translate("addBookWindow", "Economics"))
        self.cat_combo.setItemText(6, _translate("addBookWindow", "History"))
        self.cat_combo.setItemText(7, _translate("addBookWindow", "Law"))
        self.cat_combo.setItemText(8, _translate("addBookWindow", "Novel"))
        self.cat_combo.setItemText(9, _translate("addBookWindow", "Personal Evolution"))
        self.cat_combo.setItemText(10, _translate("addBookWindow", "Philosophy"))
        self.cat_combo.setItemText(11, _translate("addBookWindow", "Poetry"))
        self.cat_combo.setItemText(12, _translate("addBookWindow", "Politics"))
        self.cat_combo.setItemText(13, _translate("addBookWindow", "Religion"))
        self.cat_combo.setItemText(14, _translate("addBookWindow", "Science"))
        self.cat_combo.setItemText(15, _translate("addBookWindow", "Turkish Literature"))
        self.cat_combo.setItemText(16, _translate("addBookWindow", "World Literature"))

class Ui_bookDetailsWindow(QtWidgets.QWidget):

    def __init__(self):
        QtWidgets.QWidget.__init__(self)
        self.setupUi(self)

    def setupUi(self, bookDetailsWindow):
        bookDetailsWindow.setObjectName("bookDetailsWindow")
        bookDetailsWindow.setFixedSize(997, 418)
        bookDetailsWindow.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("media/Logom2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        bookDetailsWindow.setWindowIcon(icon)
        bookDetailsWindow.setStyleSheet("background:#80c5ed;")
        self.label = QtWidgets.QLabel(bookDetailsWindow)
        self.label.setGeometry(QtCore.QRect(120, 20, 861, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(bookDetailsWindow)
        self.label_2.setGeometry(QtCore.QRect(120, 120, 861, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.edit_but = QtWidgets.QPushButton(bookDetailsWindow)
        self.edit_but.setGeometry(QtCore.QRect(10, 10, 60, 60))
        self.edit_but.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.edit_but.setStyleSheet("background:#3e8fc9;\n"
"border-radius:10px;")
        self.edit_but.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("media/pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.edit_but.setIcon(icon1)
        self.edit_but.setIconSize(QtCore.QSize(45, 45))
        self.edit_but.setObjectName("edit_but")
        self.book_name_label = QtWidgets.QLineEdit(bookDetailsWindow)
        self.book_name_label.setEnabled(True)
        self.book_name_label.setGeometry(QtCore.QRect(120, 60, 861, 35))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(15)
        font.setItalic(False)
        self.book_name_label.setFont(font)
        self.book_name_label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.book_name_label.setStyleSheet("background:#80c5ed;\n"
"border:0px;")
        self.book_name_label.setText("")
        self.book_name_label.setReadOnly(True)
        self.book_name_label.setClearButtonEnabled(False)
        self.book_name_label.setObjectName("book_name_label")
        self.author_name_label = QtWidgets.QLineEdit(bookDetailsWindow)
        self.author_name_label.setGeometry(QtCore.QRect(120, 160, 861, 35))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(15)
        font.setItalic(False)
        self.author_name_label.setFont(font)
        self.author_name_label.setStyleSheet("background:#80c5ed;\n"
"border:0px;")
        self.author_name_label.setText("")
        self.author_name_label.setReadOnly(True)
        self.author_name_label.setObjectName("author_name_label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(bookDetailsWindow)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(120, 210, 861, 63))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.page_label = QtWidgets.QLineEdit(bookDetailsWindow)
        self.page_label.setGeometry(QtCore.QRect(560, 270, 421, 35))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(15)
        font.setItalic(False)
        self.page_label.setFont(font)
        self.page_label.setStyleSheet("background:#80c5ed;\n"
"border:0px;")
        self.page_label.setText("")
        self.page_label.setReadOnly(True)
        self.page_label.setObjectName("page_label")
        self.owned_check = QtWidgets.QCheckBox(bookDetailsWindow)
        self.owned_check.setGeometry(QtCore.QRect(120, 320, 150, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(15)
        self.owned_check.setFont(font)
        self.owned_check.setObjectName("owned_check")
        self.owned_check.setDisabled(True)
        self.read_check = QtWidgets.QCheckBox(bookDetailsWindow)
        self.read_check.setGeometry(QtCore.QRect(120, 370, 150, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(15)
        self.read_check.setFont(font)
        self.read_check.setObjectName("read_check")
        self.read_check.setDisabled(True)
        self.save_but = QtWidgets.QPushButton(bookDetailsWindow)
        self.save_but.setGeometry(QtCore.QRect(10, 120, 60, 60))
        self.save_but.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.save_but.setStyleSheet("background:#3e8fc9;\n"
"border-radius:10px;")
        self.save_but.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("media/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_but.setIcon(icon2)
        self.save_but.setIconSize(QtCore.QSize(40, 40))
        self.save_but.setObjectName("save_but")
        self.delete_but = QtWidgets.QPushButton(bookDetailsWindow)
        self.delete_but.setGeometry(QtCore.QRect(10, 230, 60, 60))
        self.delete_but.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_but.setStyleSheet("background:#3e8fc9;\n"
"border-radius:10px;")
        self.delete_but.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("media/trash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_but.setIcon(icon3)
        self.delete_but.setIconSize(QtCore.QSize(45, 45))
        self.delete_but.setObjectName("delete_but")
        self.label_6 = QtWidgets.QLabel(bookDetailsWindow)
        self.label_6.setGeometry(QtCore.QRect(10, 72, 60, 20))
        self.label_6.setStyleSheet("color:white;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(bookDetailsWindow)
        self.label_7.setGeometry(QtCore.QRect(10, 180, 60, 20))
        self.label_7.setStyleSheet("color:white;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(bookDetailsWindow)
        self.label_8.setGeometry(QtCore.QRect(10, 290, 60, 20))
        self.label_8.setStyleSheet("color:white;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.cat_combo = QtWidgets.QComboBox(bookDetailsWindow)
        self.cat_combo.setEnabled(False)
        self.cat_combo.setGeometry(QtCore.QRect(120, 270, 421, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.cat_combo.setFont(font)
        self.cat_combo.setAutoFillBackground(False)
        self.cat_combo.setStyleSheet("background:#3e8fc9;\n"
"color:white;")
        self.cat_combo.setEditable(False)
        self.cat_combo.setObjectName("cat_combo")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")
        self.cat_combo.addItem("")

        self.retranslateUi(bookDetailsWindow)
        QtCore.QMetaObject.connectSlotsByName(bookDetailsWindow)

    def closeEvent(self, event):
        self.book_name_label.setStyleSheet("background:#80c5ed;border:0px")
        self.author_name_label.setStyleSheet("background:#80c5ed;border:0px")
        self.page_label.setStyleSheet("background:#80c5ed;border:0px")
        self.book_name_label.setReadOnly(True)
        self.author_name_label.setReadOnly(True)
        self.page_label.setReadOnly(True)
        self.owned_check.setDisabled(True)
        self.read_check.setDisabled(True)
        self.cat_combo.setDisabled(True)

    def retranslateUi(self, bookDetailsWindow):
        _translate = QtCore.QCoreApplication.translate
        bookDetailsWindow.setWindowTitle(_translate("bookDetailsWindow", "Book Details"))
        self.label.setText(_translate("bookDetailsWindow", "Book Name"))
        self.label_2.setText(_translate("bookDetailsWindow", "Author Name"))
        self.label_3.setText(_translate("bookDetailsWindow", "Category"))
        self.label_4.setText(_translate("bookDetailsWindow", "Page Number"))
        self.owned_check.setText(_translate("bookDetailsWindow", "Owned"))
        self.read_check.setText(_translate("bookDetailsWindow", "Read"))
        self.label_6.setText(_translate("bookDetailsWindow", "Edit"))
        self.label_7.setText(_translate("bookDetailsWindow", "Save"))
        self.label_8.setText(_translate("bookDetailsWindow", "Delete"))
        self.cat_combo.setItemText(0, _translate("bookDetailsWindow", "Academic"))
        self.cat_combo.setItemText(1, _translate("bookDetailsWindow", "Art"))
        self.cat_combo.setItemText(2, _translate("bookDetailsWindow", "Biography"))
        self.cat_combo.setItemText(3, _translate("bookDetailsWindow", "Business"))
        self.cat_combo.setItemText(4, _translate("bookDetailsWindow", "Economics"))
        self.cat_combo.setItemText(5, _translate("bookDetailsWindow", "History"))
        self.cat_combo.setItemText(6, _translate("bookDetailsWindow", "Law"))
        self.cat_combo.setItemText(7, _translate("bookDetailsWindow", "Novel"))
        self.cat_combo.setItemText(8, _translate("bookDetailsWindow", "Personal Evolution"))
        self.cat_combo.setItemText(9, _translate("bookDetailsWindow", "Philosophy"))
        self.cat_combo.setItemText(10, _translate("bookDetailsWindow", "Poetry"))
        self.cat_combo.setItemText(11, _translate("bookDetailsWindow", "Politics"))
        self.cat_combo.setItemText(12, _translate("bookDetailsWindow", "Religion"))
        self.cat_combo.setItemText(13, _translate("bookDetailsWindow", "Science"))
        self.cat_combo.setItemText(14, _translate("bookDetailsWindow", "Turkish Literature"))
        self.cat_combo.setItemText(15, _translate("bookDetailsWindow", "World Literature"))

class Ui_questionWindow(QtWidgets.QWidget):

    def __init__(self):
        QtWidgets.QWidget.__init__(self)
        self.setupUi(self)

    def setupUi(self, questionWindow):
        questionWindow.setObjectName("questionWindow")
        questionWindow.setFixedSize(570, 180)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("media/Logom2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        questionWindow.setWindowIcon(icon)
        questionWindow.setStyleSheet("background:#80c5ed;")
        self.horizontalLayoutWidget = QtWidgets.QWidget(questionWindow)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 90, 551, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ok_but = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ok_but.setStyleSheet("background:green;\n"
"color:white;")
        self.ok_but.setObjectName("ok_but")
        self.horizontalLayout.addWidget(self.ok_but)
        self.cancel_but = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancel_but.setStyleSheet("background:red;\n"
"color:white;")
        self.cancel_but.setObjectName("cancel_but")
        self.horizontalLayout.addWidget(self.cancel_but)
        self.label = QtWidgets.QLabel(questionWindow)
        self.label.setGeometry(QtCore.QRect(10, 30, 551, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(questionWindow)
        QtCore.QMetaObject.connectSlotsByName(questionWindow)

    def retranslateUi(self, questionWindow):
        _translate = QtCore.QCoreApplication.translate
        questionWindow.setWindowTitle(_translate("questionWindow", "Form"))
        self.ok_but.setText(_translate("questionWindow", "OK"))
        self.cancel_but.setText(_translate("questionWindow", "Cancel"))
        self.label.setText(_translate("questionWindow", "Are you sure you want to delete book?"))

        self.cancel_but.clicked.connect(lambda: self.close())
